# Lab 1 | Fall 2025

**Copy and paste these questions into a document (Google Doc or Word) to answer these questions.** Please number your responses to help your GSI grade. There’s no word count, and we won’t penalize students for grammar or spelling. Do your best to explain your ideas in your own words, and if you get stuck or confused, post on Discord / ask your GSI / explain why you got stuck and what you tried to do to figure things out.

1.  Define two variables in R : one numeric, and one string. Note :  you can use the data that we collected in class, or collect your own data (make sure each variable has at least ten data points). “Print” each variable in R, and paste the output as a screenshot. Then, graph the numeric variable as a “histogram” and the string variable as a “plot”. Below your graph, describe what you observe about the individuals in the dataset for each variable. See the lecture videos in Chapter 2 for a guide on how to do this!

2.  What’s a prediction about people that you made today? What information did you use to make this prediction? How did (or could) you use this prediction to influence outcomes? Were you valid in your predictions? Finally, write a linear model that defines the prediction (and information that you used) as a formula (e.g., DV ~ IV1 + IV2 + … + error).

3.  Identify a research question that you might be interested to study as a psychologist (this could be what you wrote about in Lab 1, or something new.) Then, define the DV for this question, and explain what interests you about this question and how this variable might be understood as an example of affect, behavior, and/or cognition. Next, explain what between-person and within-person variation might look like for this variable. Finally, identify some other variables that you think will predict this DV, and write out this question (and your theory) as a linear model.

4.  **In Discussion Section.** With your discussion section,define each of the six biases described in the Goldacre (2010) reading on cognitive biases, and come up with an example from real-life.

|                        |                |                       |
|------------------------|----------------|-----------------------|
| **Bias**               | **Definition** | **Real-Life Example** |
| Positive Evidence      |                |                       |
| Previous Belief        |                |                       |
| Patterns in Randomness |                |                       |
| Availability Bias      |                |                       |
| Social Influence       |                |                       |
| Regression to the Mean |                |                       |
