---
title: "Lab 2"
format: html
---

**Copy and paste these questions into a document (Google Doc or Word).** Please number your responses to help your GSI grade. There’s no word count, and we won’t penalize students for grammar or spelling. Do your best to explain your ideas in your own words, and if you get stuck or confused, post on Discord / ask your GSI / explain why you got stuck and what you tried to do to figure things out.

1.  **Number Problems :** Graph two numeric variables from the onboarding dataset. Change the arguments on the graph to make them look “nice”. Below the graphs, describe what you learn about the individuals for each variable (no stats terminology yet!) and conclude with additional questions you have about each variable.

2.  **Health Problems.** Load the “covid_behavior_dataset.csv” (in the Chapter Dataset folder). Check to make sure the data loaded correctly with the head() function. Report the sample size and names of the variables from this dataset, and look over the code book. Choose two variables from the dataset - one numeric and one categorical - that you would be interested to learn more about. How do you think people in the dataset will differ on these variables? Then, graph each variable side by side (try to use the par() function to do this), make the graphs "look nice". Below the graphs describe what you learn about the individuals in the dataset for each variable (no stats terms yet) and conclude with additional questions you have about each variable.

3.  **Sharing Problem.** Find a buddy. If you missed discussion section, then find someone on Discord or make up a buddy in your mind and do the work for them. Organize and clean your R Code from Problem 2 such that a) only the code you need to answer Question 2 is included and b) your code is commented and organized so people can follow along with what you are doing. Share your R code another student 2. Use (or adapt) the R code to reproduce their graph. You're doing open-science!

4.  **Get Started on a Lit Review.** Use Google Scholar to search for articles related to your final project topic. Keep track of the articles somehow (here's a [simple google spreadsheet template you can use](https://docs.google.com/spreadsheets/d/1Z6bwMrtC6glf2X2A55-cq0pI-smUV5LyLy9eyDiM5nA/edit?usp=sharing); share on Discord if you find other nice ways to keep things organized. If you wanna go down a rabbit hole, try using Zotero or Paperpile.) Share a link to your annotated bibliography here, and add to column D of your discussion section's [Psych 101 Vision Board](https://docs.google.com/spreadsheets/d/1WMn8SH-yQC-5bNcnQR-Jp5RWkxutVlKNmxCgMDgompI/edit?usp=sharing) (make sure your permissions are set so others can view, but not edit, your work.)

5.  **AI Disclosure.** Please describe how you used AI tools; make sure you include specific prompts here. Thanks!
