---
title: "Lab6"
format: html
---

### Problem 1.
These data measure Midwestern college students’  implicit and explicit prejudiced attitudes toward Native Americans, and their support for a college Native American mascot considered racist by local tribes. The researchers predicted that both implicit prejudice (IV1 = IATscore) and explicit prejudice (IV2 = prejudiceNatAm) would be related to more positive attitudes toward the native american mascot (DV = attitude). Test these researchers theory.

1.  Load the data, check to make sure the data loaded correctly, and graph each variable that will be used in your models.
2.  Define a linear model to predict the variable attitudes (DV) from implicit prejudice (IV1 = IATscore). Include a graph of the linear model, and report the slope and R2 value of this model beneath this graph. 
3.  Define a linear model to predict the variable attitudes (DV) from explicit prejudice (IV2 = prejudiceNatAm). Include a graph of the linear model, and report the slope and R2 value of this model beneath this graph. 
4.  Describe what you observe about this relationship. Were the reserachers' theory supported? Why do you think these patterns exist? Which measure of prejudice (implicit or explicit) was a better predictor of the DV?

### Problem 2.
How strong is the relationship between implicit and explicit prejudice? Define a linear model to test this prediction. Then, z-score your DV and IV in the linear model, and report (and interpret) the slope and $R^2$ value. How did these statistics change (from the non-z-scored model to the z-scored model)? How did they remain the same?

### Problem 3 (On Your Own).
Identify another numeric variable from the mascot dataset that you think will predict attitudes toward the mascot. Define the linear model, report the statistics and graph needed to understand the relationship, and explain what you observe about the relationship between the two variables below.

### Problem 4 (In Discussion Section). 
Work with your classmates to identify a numeric DV that you are interested in predicting. Then, work with a buddy to choose a numeric IV that y'all think will BEST predict this DV. Write out your prediction (how do you think these two variables will be related?) Define the linear model needed to test this prediction, report the statistics and graph needed to understand the relationship, and explain what you observe below your graph. Why do you think this relationship exists? Then, z-score your DV and IV in the linear model, and report (and interpret) the slope and $R^2$ value. How did these statistics change? How did they remain the same? Compare the results of your model to another team - whose model was a "better" model? Why / how do you know?