---
title: ""
format: html
editor: visual
---

# Week 8 - Friday, March 13th

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
-   **THE END IS NEAR.** Five lectures (and an Exam) left. Actually this feels like a lot?
-   **R Exam is THREE WEEKS.** After Spring Break. See [study guide](https://docs.google.com/document/d/1myT--E0ePbygFSa3bMxzCb0sb1LnmUOM8XuGlfmq0F4/edit?usp=sharing).
-   **Discussion Section**. Milestone 2 Feedback + Working on Lab 6 (Practice Exam with a Key.)
:::

::: {.column width="50%"}
**Today, on Psych 101...**

-   **2:10 - 3:15.** Check-In and Linear Model Review.
-   **3:15 - 3:25.** Break Time.
-   **3:25 - 4:00.** Introducing Milestone #3.
-   **4:00 - 5:00.** Project Workshop.
:::
:::::
::::::

### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/calstats/Lectures/7_CatModels.html" width="100%" height="500px" title=""></iframe>
```

-   [**Check-In. Linear Model Review**](https://docs.google.com/forms/d/e/1FAIpQLSc7Q4AhxKUG0guX6vp3mqjXjsUdg1jrnMF89tIGTVxvSKdK2g/viewform?usp=dialog). Purposefully vague!
    -   [**Narcissism Data**](https://www.dropbox.com/scl/fi/p1yc5kvkckkwok2v19jl5/narcissism_data.csv?rlkey=y0zwtllmfsie447eybxa4965u&dl=0). For the check-in.
-   [**Professor Notes**](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)**.** My R scripts and other notes, saved in real-time.
-   [**Final Project Description & Rubric**](https://docs.google.com/document/d/1DxiIxm_sRtm8t5FEOWhOJluJOo6ZPUI_eZTS13K4CxA/edit?usp=sharing)**.** And here's the [Final Project Vision Board](https://docs.google.com/spreadsheets/d/1WMn8SH-yQC-5bNcnQR-Jp5RWkxutVlKNmxCgMDgompI/edit?usp=sharing).

# For Next Week.

## Discussion Section. Milestone #2 Feedback

In Discussion Section this week, you'll have a 1-on-1 meeting with your GSI to go over Milestone 2, and hopefully get approval to start Milestone 3. Yeah!

## Lab 6. Complete the Practice R Exam (In Discussion Section)

In Discussion Section while other students are working on the Practice Exam, you'll be working on the previous semester's exam as practice for our upcoming R Exam. A video key will be posted; use this after you try to complete the entire exam. Any Lab 6 submission will get full credit.
