---
title: ""
format: html
editor: visual
---

# Week 12 - Friday, April 24th

:::::: {.callout-note collapse="true"}
### Announcements and Agenda and Advertisement(s)

::::: columns
::: {.column width="50%"}
- **THE END IS NEAR!** Two classes (and a brain exam and final project) left. Whew!
- **Brain Exam is next week IN SECTION.** Will review in class and section. On interpreting regression (NHST). The learning has not stopped. But will soon.
- **RRR Week :** extra office hours in the morning; no class. next week our goodbye.
:::

::: {.column width="50%"}
**Today, on Psych 101...**

- **2:10 - 2:45.** Check-In (Multiple Regression & Brain Exam Review)
- **2:45 - 3:15.** Deeper into Multiple Regression.
- **3:15 - 3:25.** BREAK
- **3:25 - ???.** Milestone #6 & Project Time
:::
:::::
::::::

### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/calstats/Lectures/12_MRReview.html" width="800" height="500" title=""></iframe>
```

- [**Check-In. NHST Review**](https://forms.gle/H915SBtAyP18MDWB6). No R required. Just brain. Data from the covid dataset.
- [**Professor Notes**](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)**.** My R scripts and other notes, saved in real-time.
- [**Final Project Description & Rubric**](https://docs.google.com/document/d/1DxiIxm_sRtm8t5FEOWhOJluJOo6ZPUI_eZTS13K4CxA/edit?usp=sharing)**.**

# For Next Class.

## [Milestone #6](https://docs.google.com/document/d/1DxiIxm_sRtm8t5FEOWhOJluJOo6ZPUI_eZTS13K4CxA/edit?tab=t.0). A Draft

**Bring it all together.**

## [Chapter 11.](https://catterson.github.io/ystats/chapters/11R_InteractionFX.html) Optional (Interaction Effects)

No Quiz.
