---
title: ""
format: html
editor: visual
---

# Week 7 - Friday, March 6th

## Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/calstats/Lectures/6L_MascotModels.html" width="100%" height="500px" title=""></iframe>
```

-   [Check-In: Working With the Mascot Dataset](https://docs.google.com/forms/d/e/1FAIpQLSdrgiekPpIjCHqi_ALSJoZseMKC3BfkUGx2eC3QCExESX8zoQ/viewform?usp=sf_link)
    -   [Mascot Dataset and Codebook](https://www.dropbox.com/scl/fo/lioqn3vcv5wkl4c7igxlz/AOAZII2z_pt973R4DMKKdDE?rlkey=neym1p5i8x6fdudkf5lrryosg&dl=0)
-   [Folder with Professor R Scripts and Notes](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)
-   [Final Project Vision Board](https://docs.google.com/spreadsheets/d/1WMn8SH-yQC-5bNcnQR-Jp5RWkxutVlKNmxCgMDgompI/edit?usp=sharing) + [Final Project Description & Rubric](https://docs.google.com/document/d/1DxiIxm_sRtm8t5FEOWhOJluJOo6ZPUI_eZTS13K4CxA/edit?usp=sharing)

::::: columns
::: {.column width="60%"}
### Announcements and Agenda

-   **R Exam is in 4 weeks.** 2 more lectures + Spring Break. Will post study guides + practice exams. Review in section the week after spring break.

-   **Milestone #2.** Will look over some examples today / in section. Feedback in two weeks (in section).

-   **Milestone #3.** Wait to do this until you get feedback / "GREEN LIGHT" from your GSI.

-   **Lab 5.** Part of the skill is thinking through the steps.
:::

::: {.column width="40%"}
-   **2:10 - 2:35.** Check-In

-   **2:35 - 3:10.** Mascot Dataset (Part 1)

-   **3:10 - 3:20.** Break Time

-   **3:20 - 3:40.** Mascot Dataset (Part 2)

-   **3:40 - 5:00.** Final Project Workshop (Milestone 2 Review)
:::
:::::

## Due Next Week

1.  **In Discussion Section.** *Walk through* terms of reliability and validity...work on Lab 5.
2.  **Chapter 7 (Linear Models when the IV is categorical) + a Quiz.**

# Lab 5.

**Note :** part of the skill in working with data is thinking through the steps you will need to answer the question. We will practice this!

1.  In lecture, we examined the relationship between attitudes about indigenous mascots, and people's explicit and implicit prejudice. Determine whether there is a relationship between explicit and implicit prejudice. Make sure to a) include graphs of your variables and the linear model, b) report the intercept, slope (in "raw" units and as a correlation coefficient), and $R^2$ from your model, c) describe what these statistics tell you about the relationship between these two variables, and d) explain how looking at the relationship between these two variables connects to terms of reliability and validity.
2.  Choose two numeric variables from the mini dataset and see whether there is a relationship between these two variables. Make sure to a) include graphs of your variables and the linear model, b) report the intercept, slope (in "raw" units and as a correlation coefficient", and $R^2$ from your model, c) describe what these statistics tell you about the relationship between these two variables, d) explain why you think there's a relationship between these two variables, and e) conclude with any other questions you have / ideas about how to use this knowledge (e.g., what can we do knowing there is / is not a relationship between these two variables.)
