---
title: ""
format: html
editor: visual
---

## Week 2 - Friday, January 30th

### Class Slides

```{=html}
<iframe class="slide-deck" src="/calstats/Lectures/1L_WhyStats.html" width="100%" height="500px" title=""></iframe>
```

-   [Link to PDF of Slides](https://www.dropbox.com/scl/fo/sahonol5voku0vwp5qoum/AOI8Bhbbpn5MpyuxeDYEQIg?rlkey=2jfup37ml3zvs1ju3h61q8uzp&dl=0).
-   [Link to Folder with Professor R Scripts and Notes](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)

### Due Next Week

1.  Attend Discussion Section
2.  Complete and Submit Lab 1.
3.  Read [Chapter 2](https://catterson.github.io/ystats/chapters/2R_Data.html) of ***Why Statistics?*** on navigating and loading data.
4.  Complete Chapter 3 Quiz on bCourses.

# Lab 1

**Copy and paste these questions into a document (Google Doc or Word).** Please number your responses to help your GSI grade. There’s no word count, and we won’t penalize students for grammar or spelling. Do your best to explain your ideas in your own words, and if you get stuck or confused, post on Discord / ask your GSI / explain why you got stuck and what you tried to do to figure things out.

1.  **Define two variables in R : one numeric, and one string.** *You can use the data that we collected in class, or collect your own data (make sure each variable has at least ten data points).* “Print” each variable in R, and paste the output as a screenshot. Then, graph the numeric variable as a “histogram” and the string variable as a “plot”. Below each graph, describe what you observe about the individuals in the dataset for each variable and whether these graphs change how you think about the variables at all.

2.  **What’s a prediction about people that you made today?** What information did you use to make this prediction? How did (or could) you use this prediction to influence outcomes? Were you valid in your predictions? Finally, write a linear model that defines the prediction (and information that you used) as a formula (e.g., DV \~ IV1 + IV2 + … + error).

3.  **Start thinking about your final project. You can reuse work you did for Milestone 1.** A) What is a research question you are interested in, why does this question matter, and what background experiences inform your beliefs about this question? B) What is the variable that is the focus of this question? How does this variable relate to affect, behavior, and cognition? What is the between-person form of variation for this variable? What is the within-person form of variation for this variable? *Note : for the final project, I strongly recommend focusing on a between-person variation version of the variable for the final project.* C) What ideas do you have about the answer to this question? Write this out as a [linear model]{.underline}. D) How might you use this knowledge to change the world (For good? For bad?)

4.  **In Discussion Section.** With your discussion section, define each of the six biases described in the [Goldacre (2010) reading on cognitive biases](https://www.dropbox.com/scl/fi/mev9u3oyacrf21dvu48ac/Goldacre_2010_Chapter10.pdf?rlkey=vrcqb617zde7mye8un2xm184k&dl=0), apply this to the [horoscope video](https://www.youtube.com/watch?v=haP7Ys9ocTk) you will watch in discussion section, and come up with an example from real-life. Note : if you miss discussion section, you are still responsible for answering this question for the lab assignment!

|  |  |  |  |
|----|----|----|----|
| **Bias** | **Definition** | **Real-Life Example** | **Horoscope Example** |
| Positive Evidence |  |  |  |
| Previous Belief |  |  |  |
| Patterns in Randomness |  |  |  |
| Availability Bias |  |  |  |
| Social Influence |  |  |  |
| Regression to the Mean |  |  |  |

5.  **AI Disclosure.** Please describe how you used AI tools; make sure you include specific prompts here. Thanks!
