---
title: ""
format: html
editor: visual
---

## Week 1 - Friday, January 23rd

### Class Slides

```{=html}
<iframe class="slide-deck" src="/calstats/Lectures/0L_WelcomeStats.html" width="100%" height="500px" title=""></iframe>
```

### Due Next Week

1.  Attend Discussion Section
2.  Complete Milestone #1 (In Discussion Section)
3.  Read the [Introduction](https://catterson.github.io/ystats/) and [Chapter 1](https://catterson.github.io/ystats/chapters/1R_WhyStats.html) of ***Why Statistics?***
4.  Complete Quiz 1 on bCourses

### Milestone #1

**Hello! You will work on this in discussion section, so please do not start until then :)**

In this class, we have a final project, where you will identify a topic that you care about, develop this idea into a research question, design a study to answer some part of this question, collect and analyze the data from your study (using R!), and then write up the results as an academic paper. We will work on this throughout the semester - I promise it will be chill if you follow along with us!

The first step, is picking some topic or variable that you care about, and identifying the parts of your background or experiences that influence this topic. This can be a challenging first step, and it’s okay to struggle. Your topic will also change as we develop it, so don’t feel like it needs to be “perfect” or “locked in” yet.

You can read some more on identifying a project topic in [Part 3 of Chapter 1Links to an external site.](https://catterson.github.io/ystats/chapters/1R_WhyStats.html#step-1-identify-a-question).

***Upload your responses to the following questions to the Milestone #1 Assignment on bCourses :***

1.  **What's your first memory of a computer?** What have been your experiences with computers, statistics, or research? How do these experiences influence your preparedness and goals for this class? 

2.  **What is one topic or question about people (or non-human animals) that interests you?** Why do you care about this topic, and how is this topic related to your past experiences?

3.  **What variable is the focus of this question?** Are you interested in the AFFECT, BEHAVIORAL, or COGNITIVE aspect of this variable?

Don't spend too long on this :) the point is to just start thinking about your project, and let professor pull out a few examples for class. You can always change your topic idea later.
