---
title: ""
format: html
editor: visual
---

# Week 4 - Friday, February 13th

## Class Slides and Materials

```{=html}
<iframe class="slide-deck" src="/calstats/Lectures/3L_Description.html" width="100%" height="500px" title=""></iframe>
```

-   [Link to Interruption Codebook and Dataset](https://www.dropbox.com/scl/fo/9ddzw0iqwing82enm84si/AHHOgMBFfouetcII0CFgog0?rlkey=2qgi0zbrvbwuam5v3k65t971q&dl=0)
-   [Link to Folder with Professor R Scripts and Notes](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)
-   [Link to Final Project Vision Board](https://docs.google.com/spreadsheets/d/1WMn8SH-yQC-5bNcnQR-Jp5RWkxutVlKNmxCgMDgompI/edit?usp=sharing)

## Due Next Week

1.  In Discussion Section, Practice for Brain Exam + Work on Lab 3
2.  Complete and Submit Lab 3
3.  Read [Chapter 4](https://catterson.github.io/ystats/chapters/3R_Description.html) of ***Why Statistics?*** on Descriptive Statistics.
4.  Complete Chapter 4 Quiz on bCourses.

# Lab 3

Use R to answer the following questions. Make sure that you show your R code and the output (result or graphs.) You can do this by taking a screenshot and pasting into your Google / Word Document, or (for students wanting an extra challenge) working in a Quarto document.

## Problem 1. Interruption Problems.

**Download the “interruption” data from bCourses, and import this data into R. This dataset has two variables of the number of interruptions counted before (int1) and after (int2) our operationalization.**

1.  Load the data (I'll call it d if you want to follow along with my code), check to make sure it loaded correctly, and report the sample size and names of the variables.
2.  Graph these variables as a histogram (use the par() function to graph them side by side). Change the arguments so the graphs have the same x-axis and y-axis ranges, and nice labels.
3.  Report the mean, median, range, and standard deviation for each variables. Add vertical lines to your graphs above that illustrate the mean (in red), the median (in blue), and the standard deviation (in dashed red).
4.  Describe how these statistics changed after operationalizing an interruption, and why these changes make sense given the nature of our operationalizations. Then, explain why the median is closer to the mean for Time 2.
5.  Just to make sure we can still do this, graph a categorical variable from the dataset, report the frequency of each group, and describe what you learn from the distribution.

## Problem 2 (In Discussion Section). Mini Problems

Load the mini dataset (in the class dataset). Check to make sure the data loaded correctly. Then, choose two variables from the mini dataset. Graph each variable as a histogram, and report the mean, median, standard deviation, and range. Make sure to do any necessary data cleaning (e.g., outlier removal), and make the graphs look nice. Below each graph, describe what the statistics teach you about the people in the dataset.

## Problem 3. More Brain Exam Practice.

[Here's a link to a previous semester's BRAIN EXAM](https://docs.google.com/document/d/1U6hmo9fdHqn8UEXsueaR7HUPYQoaZbcKVP8pP9eS1IE/edit?usp=sharing). Answer the questions, and use the key (posted to the partial key) to review your answers. For this problem, just explain how the practice exam went for you. Note that each semester's exam will be a little different.

## Problem 4 (In Discussion Section). Mode Problems

R does not have a built-in function to calculate the mode. Use your favorite search engine to find a method - make sure to cite your source, and describe what you learned from the code that you found. Then check that your method works by defining two variables in R - one with a set of numbers that has one mode, and one with a set of numbers that has two modes. \[For example : variable1 \<- c(1, 1, 2) has two modes\]. Use the mode function on each variable to confirm that the mode function works. Then, use the mode function on the variable you focused on in Problem 2.

## AI Disclosure.

**Please describe how you used AI tools; make sure you include specific prompts here. Thanks!**
