# Psych 205 (Graduate Statistics - SP25)

Hi class! Welcome to our class.

## Course Information

-   **Professor \|** Arman Daniel Catterson, PhD \[he / his / او \] 🐱(catterson\@berkeley.edu)

    -   **Lectures :** Fridays 9:00 - 12:00 PM in 1213 Berkeley Way West
    -   **Office Hours :** Mondays 10:30 - 11:30 AM on Zoom (e-mail / chat after class to find another time)

-   **Teaching Assistant \|** Sierra Semko Krouse \[she / her\] \| sierra_semko\@berkeley.edu

    -   **Sections :** Fridays, 1:00 - 2:00 PM in 1213 Berkeley Way West
    -   **Office Hours :** Wednesdays 2:00 - 3:00 PM via Zoom (click here to sign-up for a 15-minute slot)

## Semester Agenda

| Week | Lecture Topic | Assignment | **Support Readings** |
|------------------|------------------|------------------|-------------------|
| 1/24 | Introduction to Data and Analysis (in R) | Lab 1 + Lab 1 Key | WS 1-2; LSR 3-4 |
| 1/31 | Description | Lab 2 | WS 3-4; LSR 5-6 |
| 2/7 | Visualizing Data in ggplot2 | Lab 3 | [Data Viz Chapter](https://ggplot2.tidyverse.org/#learning-ggplot2) |
| 2/14 | Probability and Sampling Error | Lab 4 | WS 8; LSR 9-10 |
| 2/21 | Mini Exam + Linear Models Pt. 1 (Lines!) |  | WS 5-7; LSR 15.1 - 15.2 |
| 2/28 | Linear Models Pt. 2 (Tests & Assumptions) | Lab 5 | LSR 15.5 - 15.11 |
| 3/7 | Linear Models Pt. 3 (Multiple Regression) | Lab 6 | WS 9; LSR 15.3 |
| 3/14 | Linear Models Pt. 4 (Logistic / GLM) | Lab 7 | [Generalized Linear Models](https://m-clark.github.io/book-of-models/generalized_linear_models.html) |
| 3/21 | Review / Catch-Up :) | Lab 8 |  |
| 3/28 | **Spring Break!!!** |  |  |
| 4/4 | Mega Exam | Milestone 1 |  |
| 4/11 | Linear Models Pt. 5a (Mixed Models) | Lab 9 | [Mixed Models with R](https://m-clark.github.io/mixed-models-with-R/introduction.html#overview) |
| 4/18 | Linear Models Pt. 5b (Mixed Models) | Milestone 2 | [Mixed Models with R](https://m-clark.github.io/mixed-models-with-R/introduction.html#overview) |
| 4/25 | PCA / FA | Lab 10 | [Core SEM](https://m-clark.github.io/sem/graphical-models.html) |
| 5/2 | Conclusion / Project Workshop | Project Due |  |

Note : Support Readings are assigned from my undergraduate text [Why Statistics?](https://docs.google.com/document/d/1dpODY7iojvMeQMS9xiAo9cThAL7Zz1iLFMXimb-0gbk/edit?usp=sharing) (WS) and <https://learningstatisticswithr.com/book/> (LSR) for students looking for more support.

## Grade Details

Your grade in the class will be based on the following components.

|                     |                         |                           |
|---------------------|-------------------------|---------------------------|
| 10% Attendance      | 30% R Exams \[10 + 20\] | 10% Article Presentations |
| 20% Lab Assignments | 20% Final Project       | 10% Article Discussions   |

Letter grades will be based on the following : A+ is \> 96.5; A is \> 92.5; A- is \> 89.5; etc. Note that an 89.49999 is a B+.)

## Summary of Course Components

-   **Attendance (Lecture and Discussion Section):** Because we all learn from each other; attendance is required. You may miss up to two lectures and two discussion sections with no penalty.

-   **Article Discussion.** Each week, students will be responsible for leading class discussion of one article. All students should plan to read the article, and post comments to a discussion forum on bCourses. See the [Student Presentation \| Description and Rubric] for a list of articles, a link to sign up, and a description of what is required for these student-led presentations. Let me know if you have other ideas for ways to engage the class in discussion about an article (or another article you think you would be good for the class to read.)

-   **Lab Assignments :** Most weeks, you will work through a “lab” assignment that is designed to help practice the skills we review in lecture and readings. You can expect to work on these in lecture, in your discussion section, and at home as needed. Each lab document will have a set of questions to answer - you should submit answers to these questions as a separate document to bCourses. Lab assignments are due the week after they are assigned; late lab assignments will not be accepted. You can drop your lowest submitted lab assignment.

-   **Final Project (Research Paper) :** You’ll apply the skills you have learned this semester to analyze, interpret, and share results from a research question relevant to your research interests. There will be several milestones to support this assignment. See the [Final Project \| Description and Rubric] for more information.

-   **R Exam :** For each exam, I’ll give you a novel dataset and you’ll use R to answer questions based on the dataset. The exam will be open-book and open note - you must work alone, but may use any resource available to you (including the Internet). A practice exam will be posted at least one week before the exam. The mini exam should take no more than 50 minutes to complete (we will have class afterward), and you will have the full 3-hours to complete the mega exam.

-   **Extra Credit :** There will be no extra credit offered in this course, even for students who ask kindly. 

## Course Policies

-   **Computer Access.** Access to a personal computer is strongly recommended. We will spend time each lecture working in R - a free and powerful statistics program that works with all operating systems and computers. Laptops are available for rent from the library (see Berkeley’s Technology Loan Program), or you can purchase one that will work for this class for as little as \$150 (less than the price of most textbooks, which is not required for this class).

-   **Late Work Policy.** Late assignments will not be accepted. You may drop your lowest scoring lab assignment. Let me know if you cannot attend the exam and we can schedule a make-up exam.

-   **Discussion Section Policy :** In-person attendance is expected and required for discussion sections. Students may miss up to two discussion sections with no penalty. Please talk to your GSI / the professor if there is a longer-term illness or issue that will prevent you from regularly attending your discussion section and we will work out another arrangement.

-   **Regrades.** Students may ask for a re-grade on exams and papers if they believe they lost points for something they should have earned. To request a regrade, talk to your GSI in office hours or set up a meeting. In the case that you and your GSI cannot resolve the regrade issue, the professor will step in and regrade the exam. For final project regrades just e-mail the professor. When requesting a regrade, you consent to have your score increased or decreased if we find that you earned points you should not have earned.

-   **Student Contact.** It is your responsibility to regularly check e-mail for announcements. If you have specific questions to e-mail me, please make sure to (a) search the syllabus and / or Google for the answer to your question and (b) contact your GSI about your question. I am always happy to answer any questions in office hours (either during the scheduled time or online by appointment), or before, during, or after lecture. I should respond to e-mail within 24 hours on weekdays (I do not check e-mail on weekends); please send a gentle reminder if I do not respond in this timeframe. Thanks!

-   **Academic Integrity.** Do NOT cheat. Do NOT plagiarize. To copy text or ideas from another source (including your own submitted coursework) without appropriate reference is plagiarism. You may work on lab assignments with other students, but should be able to understand what you are doing. You may not work with other students on the R exam. Anyone caught cheating or plagiarizing will receive a zero on the assignment or test, and will be reported to the Office of Student Conduct. It is your responsibility to read the official Student Conduct Policy for more information about campus standards and policies regarding Academic Integrity.

-   **Chat-GPT / AI Policy.** If you use ChatGPT or other generative-AI software for any part of this class (writing, coding, troubleshooting, etc.), you must make this clear at the top of your assignment by writing : “I USED CHAT GPT TO SUPPORT THIS ASSIGNMENT” (in all-caps and red text), and include an appendix where you include screenshots of your specific queries and answers. Failure to do this will result in a zero of the assignment, and the professor submitting a report to the Academic Integrity Office. Ask your GSI / professor if you have questions about this policy.

-   **Respect for Others.** We all belong in our classroom, and I hope that everyone feels free and supported to express our identities when relevant. To achieve this goal, make sure that you are treating others with respect in this course. This means considering others’ opinions and perspectives, making sure not to generalize to groups (or ask students to be representatives of their group), and being mindful of the words that you use. (Also remember that nothing is ever really deleted from the internet, so please be extra mindful of the words you use.) While I will be monitoring class posts and communication, feel free to reach out to me if you see another student engaging in disrespectful or threatening behavior. Of course, this extends to me as well - if you feel like there are parts of the course instruction, subject matter, or class environment that create barriers to your success or inclusion, please contact me via e-mail and trust that your voice will be heard and I will not punish you for offering constructive criticisms of my teaching. I’m very open to learning how to be a better teacher, and always learn a lot from my students.

-   **Sensitive Subjects.** Our class will touch on important and potentially sensitive topics that are related to psychology and psychological processes, such as racism, depression, sex, and poverty. These topics can generate strong emotional responses in students for a variety of reasons - such as their own past histories with these topics or their reactions to the ways the information is presented or described. I will try to make sure to give you a heads up when we start to discuss these topics so you can be mindful of your reactions.

-   **Strategies for success.** Do your readings, complete assignments on time, understand how the topics and information relate to what you’ve learned (and are learning), and if you don’t understand something, please ask the question!

-   **Most important.** Please let me know as soon as there is anything going on in your life that you think may affect your ability to do as well as you would like in this class (e.g. sickness, work, small children at home, threats to immigration status, etc.), and I will do my best to work with you on a plan to succeed in the class. If you're not comfortable talking to me directly, you can talk to your GSI who can talk to me about your issue.

## Student Support Services

-   **Students with Disabilities :** Students who require support or adaptive equipment because of a specific disability -- or would like to be tested to see if they qualify for a learning, auditory, or visual disability -- can request these services through the Disabled Students Program (DSP) office. Please note that I can only provide accommodations authorized by the DSP office. If you have DSP status, make sure you submit your letter and feel free to talk to me or a GSI about any specific accommodations you need, or other ways we might be able to make the class more accessible. \[260 César E. Chávez Student Center\| 510-642-0518 \| <https://dsp.berkeley.edu/>\]

-   **Students with Mental Health Issues :** If you feel a mental health issue (e.g., depression, anxiety) is negatively impacting your ability to succeed, I’d highly encourage you to seek out experts who can help. Berkeley has several free, confidential, and science-based programs designed to help students. \[<https://uhs.berkeley.edu/caps> \| Tang Center 3rd Floor \| 510-642-9494 \| After hours support line : 855-817-5667\]

-   **Undocumented Students :** I believe that all people deserve equal access to education. The UC Berkeley Undocumented Student Program has organized resources to support undocumented students, protect their rights, and offer potential financial aid \| <https://undocu.berkeley.edu/>

-   **Students from Low-Income Backgrounds :** The Extended Opportunity Program (EOP) provides college support services for low-income students. Services include additional counseling, financial assistance (study-time parent grants, work-study assignments, and book vouchers), child-care opportunities, and assistance transferring to four-year colleges. \[119 César E. Chavez Student Center \| 510-642-7224 \|  <https://eop.berkeley.edu/>\]

## **Final Project \| Description and Rubric**

The goals of this final project are to 1) demonstrate the research and data analytic skills that we have learned in this class, and 2) work on something that will be useful to your research career. 

*Note : this is my first semester assigning this assignment for a graduate course, and open to other ideas about how this assignment might better serve as a relevant reflection of what you have learned in the class, and your interests as a researcher.*

|  |  |
|-----------------------------------------------------|-------------------|
| **Criterion** | **Points \[Out of 4\]** |
| Student specified a specific research question to ask, articulated how this research question is relevant to their interests, background, and past psychological research, and identified a dataset that will allow them to answer this research question. |  |
| Student submitted a pre-registration plan that details the data cleaning and analyses they expect to do in order to answer their research question, a list of a post-hoc analyses that deviated from the pre-registered plan, and a link to the data and RCode. |  |
| Student conducted analyses appropriate to the research question, organized these analyses in a table, and explained the results of these analyses (descriptive, predictive, and inferential statistics). |  |
| Student included clear, presentation-ready figures to illustrate their key analyses (descriptive, predictive, and inferential statistics). |  |
| Student shared the project in a way that clearly communicates their findings and why they matter (to psychological research and / or society), articulates limitations of the project, and advances next steps / future research directions they might pursue. |  |

## **Student Presentation \| Description and Rubric**

[**Sign-Ups + List of Readings**](https://docs.google.com/spreadsheets/d/1zQClUHVzmYOMETVwGsFGnDNCX-eMeBQ6nby46EPyHEM/edit?usp=sharing) 

Each week, I’ve assigned an article for the class to read. (Let me know if you have ideas for other articles to read in this / future semesters!)

-   All students will submit discussion responses by Wednesday at noon; these discussion posts should demonstrate you have done the reading, and highlight a question or discussion topic you think would be good to focus on more in class.

-   A small group of students will be responsible for organizing a 15-20 minute presentation and discussion on the assigned article, based on the reading and submitted student discussion posts.

This presentation will be graded on the following criteria. Though I’m very open to ideas and suggestions about alternative ways you think we could effectively use this time!

|  |  |
|----------------------------------------------|--------------------------|
| **Criterion** | **Points \[Out of 4\]** |
| Students gave a quick (5 min) summary of the key points from the assigned article. |  |
| Students drew from submitted discussion posts to lead a class discussion that helped answer common questions, debate ideas, and connect readings to our work as researchers. |  |
| Students organized a presentation and / or handout to help guide audience understanding. |  |
| Student presentation demonstrated preparation, organization, thought, and coordination among group members. |  |
| Students completed the self- and peer-evaluation form. |  |

\
\

\
