---
title: ""
format: html
editor: visual
---

## Week 3 - Monday, September 14th

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
-   **DISCORD IS BUMPIN :** students (*and sometimes professor*) helping students with the R stuff; the real stuff; the gobears stuff.

-   **Brain Exam in Two Weeks (in section after the Chapter 4 lecture.)**

    -   We will practice in class and in section. Gonna be chill.

    -   If can't attend section; talk to your GSI (best : take in another one of their sections.)

    -   **DSP :** you'll have extra time (and quiet space) as needed. Went well last year

:::

::: {.column width="50%"}
**AGENDA FOR TODAY**

-   **3:10 - 3:30.** Check-In & Review

-   **3:30 - 4:10.** Working with Data Using Computer Tool (R)

-   **4:10 - 4:20. BREAK TIME #1.** Long break.

-   **4:20 - 5:00.** Operationalization, Construct, and Measurement, Oh My!

-   **5:00 - 5:30.** Getting started on literature reviews.

-   **5:30 - 6:00.** Research Questions & Farewell
:::
:::::
::::::


### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/calstats/slides/2L_WorkingWithData.html" width="100%" height="500px" title=""></iframe>
```

- [**CHECK-IN : tinyurl.com/againmodels**](https://docs.google.com/forms/d/e/1FAIpQLSeRxOyLnGN7GO7ZQYziTuElo8k39b1feE915glmQMqI-1JBTA/viewform?usp=sf_link)
- [Link to Onboarding Codebook and Dataset](https://www.dropbox.com/scl/fo/u8zr1swbl700sml2f1acp/AN0R4J7tyLqrIaUvDCAxDZs?rlkey=yhbjcobmlm8he9eu3i19mdiv7&dl=0)
- [Link to Annotated Bibliography Template](https://docs.google.com/spreadsheets/d/1Z6bwMrtC6glf2X2A55-cq0pI-smUV5LyLy9eyDiM5nA/edit?usp=sharing)
- [Link to Folder with Professor R Scripts and Notes](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)

### This Week

1.  Attend Discussion Section
2.  Complete and Submit [Lab 2](/calstats/labs/Lab2.html)
3.  Read [Chapter 3](https://catterson.github.io/ystats/chapters/3R_Description.html) of ***Why Statistics?*** on Descriptive Statistics.
4.  Complete Chapter 3 Quiz on bCourses.
