---
title: ""
format: html
toc: false
editor: visual
---

## Week 1 - Monday, August 31st

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
**Welcome! Please complete the following :**

- **Section Swap :** post on bCourses to find someone to swap with.
- **Waitlisted Students :** Thanks for your patience! Go bears.
- **Join the Class Discord :** link on bCourses
- **Next Week :** No class; Yes Section (and Chapter 2 Reading + Quiz)
:::

::: {.column width="50%"}
**AGENDA FOR TODAY**

- **10 Minutes :** Check-In and Hello!

- **60 Minutes :** Who and Why and What Statistics?

- **10 Minutes :** Break Time

- **45 Minutes :** Why R?

- **REMAINING TIME :** So you think you want to be a researcher?? \[Tips for undergrads\]
:::
:::::
::::::

### Class Slides and Materials

```{=html}
<iframe class="slide-deck" src="/calstats/slides/0_WelcomeStats.html" width="100%" height="500px" title=""></iframe>
```

- **link to these notes** : tinyurl.com/welcome101class
- [**check-in survey**](https://docs.google.com/forms/d/e/1FAIpQLSdUFSyKnQBLoCZKxb9ZqzmwbEUo8gCqtwKAEaf-wJAfoVKlbA/viewform?usp=header) **:** tinyurl.com/hifirstclass

### To-Do

1.  Attend Discussion Section
2.  Complete [Milestone #1](/calstats/labs/Milestone1.qmd) (In Discussion Section)
3.  Read the [Introduction](https://catterson.github.io/ystats/) and [Chapter 1](https://catterson.github.io/ystats/chapters/1R_WhyStats.html) of ***Why Statistics?***
4.  Complete Quiz 1 on bCourses
