---
title: ""
format: html
editor: visual
---

# Week 4 - Monday, September 21st

:::::: {.callout-note collapse="true"}
## Announcements and Agenda

::::: columns
::: {.column width="50%"}

- **Brain Exam in One Weeks (in section)**

  - Practice exam this week. Gonna be chill.

  - If can't attend section; talk to your GSI (best : take in another one of their sections.)

  - **DSP :** you'll have extra time (and quiet space) as needed. Went well last year
:::

::: {.column width="50%"}
**AGENDA FOR TODAY**

**Agenda**

-   **3:10 - 4:00.** Check-In & Interruption Data

-   **4:00 - 4:10.** BREAK TIME

-   **4:10 - 5:00.** Prediction & Error

-   **5:00 - 5:05.** MINI BREAK

-   **5:05 - ???6:00.** Project Workshop

:::
:::::
::::::

## Class Slides and Materials

```{=html}
<iframe class="slide-deck" src="/calstats/slides/3L_Description.html" data-external="1" width="100%" height="500px" title=""></iframe>
```

- [Link to Interruption Codebook and Dataset](https://www.dropbox.com/scl/fo/9ddzw0iqwing82enm84si/AHHOgMBFfouetcII0CFgog0?rlkey=2qgi0zbrvbwuam5v3k65t971q&dl=0)
- [Link to Folder with Professor R Scripts and Notes](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)
- [Link to Final Project Vision Board](https://docs.google.com/spreadsheets/d/1WMn8SH-yQC-5bNcnQR-Jp5RWkxutVlKNmxCgMDgompI/edit?usp=sharing)

## After Class

1.  Attend Discussion Section : Brain Exam Practice + Work on Lab 3
2.  Complete and Submit Lab 3
3.  Read [Chapter 4](https://catterson.github.io/ystats/chapters/3R_Description.html) of ***Why Statistics?*** on Descriptive Statistics.
4.  Complete Chapter 4 Quiz on bCourses.
