---
title: ""
format: html
editor: visual
---

# Week 5 - Monday, September 28th

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
**Brain Exam is THIS WEEK IN SECTION**

- first part of class : work on Lab 4 (and use as a Brain Exam review)

- brain exam part of class : brain exam

- last part of class : work on introduction outline
:::

::: {.column width="50%"}
**AGENDA FOR TODAY**

- **3:10 - 3:50.** Check-In & Chapter 4 Review

- **3:50 - 4:10.** Working with Quarto (IF TIME)

- **4:10 - 4:20.** BREAK TIME

- **4:20 - ????**. Milestone #2 (Intros) and then go home.
:::
:::::
::::::

## Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/calstats/slides/4L_Methods.html" width="100%" height="500px" title=""></iframe>
```

- [Link to Mini Dataset and Codebook](https://www.dropbox.com/scl/fo/1w45rzaqli7msuapkmhs9/AGCJPqypXuOUTSp5v_IQUd4?rlkey=j56w7y2g4ftbkz6bts56ba3k5&dl=0)
- [Link to Folder with Professor R Scripts and Notes](https://www.dropbox.com/scl/fo/gl6k038pu9duy75jvq1t0/ALCXZvj5iBfl0uCRfZfZiHM?rlkey=kon74xzou91hkhgx8tfjmdet5&dl=0)
- [Link to Final Project Vision Board](https://docs.google.com/spreadsheets/d/1WMn8SH-yQC-5bNcnQR-Jp5RWkxutVlKNmxCgMDgompI/edit?usp=sharing)

## [Lab 4](/calstats/labs/Lab4.html)
You'll prepare a 1-page report to analyze the mini class dataset, and get started on Milestone 2.

## Due Next Week

1.  **In Discussion Section :** Brain Exam + Work on Lab 4 (& Milestone 2, Part 1)
2.  **Complete and Submit Lab 4.** You should hopefully finish this in section
3.  **Read Chapter 5, Parts 1 and 2.** No Quiz :)
