---
title: "Lab 4"
format: html
---

**Note : This lab reviews content from Chapter 6.**

- Submit a PDF that answers the questions below. Please number your responses to help the reader grade.

- Copy and paste your R code as a comment when submitting your assignment.

- Reach out if you have any questions, or something is unclear. Thanks!

## Happiness Problems.

These questions use the "World Happiness" dataset from Lab 3. Feel free to re-use any code you used in Lab 3. Make sure to load the dataset, and check to make sure the data loaded correctly :)

**Define three separate linear models to predict SWLS_24 from the variable `Child.Mortality` (Model 1), the variable `SWLS_23` (Model 2), and the variable `Population` (Model 3).** Look to the codebook for a review of what these variables measures. 

**Make sure to do the following for each linear model : **

-   Graph your DV and IVs as separate variables using the hist() function. Make sure there are no errors in the data, and you understand the graphs you are looking at.

-   For each linear model, define the relationship between the two variables using the lm() function.
    
-   Graph the relationship between the two variables using the plot() function (make sure to input the full equation, not the model object, to plot) and add the regression line to the graph using the abline() function (input the model object to this!) See if you can use the par() function to print your graphs side-by-side in a 1x3 grid.

-   Underneath the graph, report the intercept, slope, and $R^2$ value from each model. Describe what each of these statistics tells you about the relationship between these two variables (making sure to reference the relevant statistics reported above.)

-   Finally, use your human brain to make some conclusions. What seems important about these relationships? Why do you think these relationships occur? How might we use this knowledge? What other questions do you have?