---
title: "1 | Welcome to MaCSS!"
format: html
editor: visual
---

::: callout-tip
## Objectives This Week

- Introductions to the course, the professor, and the other students. Hello!
- Learn about the goals of science, why statistics is required for social scientists to help achieve these goals.
- Get started working in R to define and graph variables.
- Start thinking about how you might want to use your training to answer a research question. 
:::

## Professor Says Hi

In this video, I say hi and introduce myself, provide an overview of the course (and the course materials we will be using to learn this summer), and a few highlights from the syllabus.

<div style="position: relative; padding-bottom: 62.5%; height: 0;"><iframe src="https://www.loom.com/embed/ac6a87d0ca48485085d86becb3bc878e" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

## To-Do

### Read the Chapters Below!

1.  [**Why Statistics Introduction.**](https://catterson.github.io/ystats/) In this chapter, you'll go over the goals of the course, and how to navigate the R programming language that we will be using to conduct statistics in this class.
2.  [**Why Statistics Chapter 1.**](https://catterson.github.io/ystats/chapters/1R_WhyStats.html) In this chapter, you'll learn how and why science is used by people in positions of power to study variation in ways that help them gain knowledge and influence the world, and how to use the programming language R to define and graph a variable to illustrate variation.

### Complete These Assignments

1.  **Complete Quiz 1 (on bCourses).** This quiz reviews some of the key terminology from the Introduction and Chapter 1 of *Why Statistics* related to the science, statistics, and the programming language R. You'll also use R to answer a few questions. The quiz is open-note and allows for multiple attempts.
2.  [**Complete Lab 1** (submit on bCourses)](/COMPSS202/Labs/Lab1.qmd)**.** This week's lab assignment asks you to define and graph two variables in R, share your code, and then join our class discord (see bCourses for the link to join).
3.  **Community Discussion Post on the [Vision Board](https://docs.google.com/spreadsheets/d/1ekZrJ7PubP1h9zkEKDiOF1Q7eVWwd70ksuk2Wrd8pmk/edit?usp=sharing).** Post your responses to the community discussion prompts below on this week's vision board tab.
    - **YOUR POST :** What’s a question you have about the world? What variable is the focus of this question? Are you most interested in the AFFECT, BEHAVIOR, or COGNITIVE aspect of this variable? What would between-person and within-person variation look like for this variable?

    - **YOUR REPLY (to another student) :** Say Hi! Consider how knowledge of this topic might be used to PREDICT and / or CONTROL people’s outcomes. In other words, how could we use knowledge about this variable to impact the world?
4.  [**Check-In: Exit Survey.**](https://forms.gle/3TgcjazrvELDuzqm9) Finally, a few survey questions to let me know how this first week of material went for you!

## Common Questions and/or Additional Resources

**I'm having trouble getting R to work!**

1.  Make sure you are downloading both R and RStudio. These are two separate programs you will need to install.
2.  Alternatively, you can set up a free account with posit.cloud. This is a cloud-based version of RStudio (and R). If you run out of free hours, you may need
3.  Reach out to me or the reader on discord, or set up a time to meet in office hours. We are here to help!
