---
title: "3 | We are Describing Data"
format: html
editor: visual
---

::: callout-tip
## Objectives This Week

- Continue practice loading datasets and graphing variables from datasets.
- Using your human brain to think about what you observe in the graph, and connecting fancy statistics to those observations)
- Critically evaluating when, why, and how "normal" distributions occur in the social sciences, and when and why they do not occur.
:::

## Professor Says Hi

In this video, I recap some of the themes I observed from the work y'all submitted in Week 3, and introduce what we will learn this week!

::: {style="position: relative; padding-bottom: 62.5%; height: 0;"}
<iframe src="https://www.loom.com/embed/a2847ac081d44339bb67a8fab11071d5" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">

</iframe>
:::

## To-Do

### Read the Chapters Below!

**Note : this is the only week we will have two chapters to read!** They are each shorter than the previous chapters, so hopefully don't take you too long. Let me know how it goes.

1.  [**Why Statistics Chapter 3**](https://catterson.github.io/ystats/chapters/3R_Description.html)**.** In this chapter, we'll review descriptive statistics, and connect them to our graphs and observations of data.
2.  [**Why Statistics Chapter 4 (Parts 1 and 2).**](https://catterson.github.io/ystats/chapters/4R_NormalPeople.html) In this chapter, we'll discuss what it means for a distribution to be "normal", and how / why / when that normal distributions occur.

### Complete These Assignments

1.  **Complete the Chapter 3 and Chapter 4 Quizzes (on bCourses).** There are two quizzes this week! One for each chapter. In each quiz, you'll continue practicing load a dataset into R and use it to calculate some descriptive statistics like the mean, median, and standard deviation. Each quiz has a practice quiz with a video key in the chapter you can use to prepare (like the Chapter 2 Quiz).
2.  [**Complete Lab 3 (submit on bCourses)**](/COMPSS202/Labs/Lab3.qmd)**.** This week's lab assignment asks you to graph a variable from the "World Happiness" dataset, conduct descriptive statistics, explain what these statistics "teach" you about the distribution, and then feed the graph into some AI tool and see what AI says. Fun!
3.  **Community Discussion Post on the [Vision Board](https://docs.google.com/spreadsheets/d/1ekZrJ7PubP1h9zkEKDiOF1Q7eVWwd70ksuk2Wrd8pmk/edit?usp=sharing) (Make Sure to Click the Week 3 Tab).** Post your responses to the community discussion prompts below on this week's vision board tab.
    - **YOUR POST :** Download the "MaCSS Mini Class Dataset" (posted to bCourses under "Course Materials"). Load the dataset into R, and name the dataset `d` when importing it into R. Choose a [numeric]{.underline} variable to graph from the dataset and summarize in the Vision Board. For this variable, please complete the following : a) graph the variable (and make the graph look nice!); b) report the mean and standard deviation for the variable; c) explain what you learn about the students in the class from the distribution (connecting these to some stats terms), and d) consider the "Random" and "Non-Random" reasons for variation that might occur (see Chapter 4, as well as my example video below).

    - **YOUR REPLY :** Reply to another student in the class - use their code to regenerate the graph. Then, change some feature of the graph. Finally, identify another numeric variable from the same dataset that you think might help predict or explain variation in the original variable (No R is required for this last step; we will learn how to do this next week!)

    - [**PROFESSOR EXAMPLE VIDEO**](https://www.loom.com/share/1faf443848ec4d7b9bde1096e8e2997c) **:** I'll did this assignment for one of the variables, recorded a video, and posted it as a guide :)
4.  [**Check-In : Exit Survey and Reflecting on AI for Lab 3**](https://forms.gle/FgaL1NdygSKN59hK9). I've decided I like and need the weekly feedback about how the class is going, so kept the same questions from last week. I'd also love to hear how Lab 3, Question 5 went for you :). Will report back in next week's "Professor Says" video.

## Common Questions and/or Additional Resources

**Questions and Resources from Week 2.** A few things students asked for in the Check-Ins.

- [**A video on the par() function**](https://youtu.be/ou0-Je8uDdA)**.** Using the hormone dataset. Let me know if you have further questions!

- **Submitting Lab Work.** For now, just report the relevant statistics (e.g., what was the mean?) alongside your interpretation, and paste screenshots of any graphs. To submit your code, copy the code from your R script and paste it into the comment on bCourses. Let me know if you have questions on Discord; thanks!

**Chapter 3 Videos**

- Conceptual Understanding

  - [The mean as prediction](https://youtu.be/sK6_vcs23I0)

  - [Residuals as error](https://youtu.be/AGl7jo3WRJY)

  - [Sum of Squared Residual Errors](https://youtu.be/hN5opflzXIA)

  - [Standard Deviation is the Average of the Un-Squared Sum of Residual Errors](https://youtu.be/4SQUK8GXwrI)

- Practice

  - [Describing World Happiness](https://youtu.be/Te1ChWgiATU)

  - [Variation in World Happiness](https://youtu.be/Pm8Z2z6QWMs)

  - [Practice Quiz Video Key](https://youtu.be/L3kQXfp2jNg)

**Chapter 4 Videos**

- Conceptual

  - [Z-Scores](https://www.youtube.com/watch?v=wPX4tlDLXjE)

  - [Removing Outliers](https://youtu.be/Hi0C8M5398Q)

- Practice

  - [Describing the "War" Dataset](https://youtu.be/nEdJvrwV0GQ)

  - [Variation and Outliers in the "War" Dataset](https://youtu.be/Y20eLKQmnew)
