---
title: "8 | Summer Assessment (R Exam)"
format: html
editor: visual
---

::: callout-tip
## Objectives This Week

- End the class with a final assessment (the R Exam)
- Say goodbye!
:::

## Professor Says Goodbye

Hello! In this video, I say goodbye for the summer.

::: {style="position: relative; padding-bottom: 62.5%; height: 0;"}
<iframe src="https://www.loom.com/embed/4f34c77d350a4cafa97127a9fa1b755f" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">

</iframe>
:::

## To-Do

### Complete These Assignments

1.  [**Take the R Exam**](https://catterson.github.io/COMPSS202/Labs/RExam.html)**.** Similar to last week's practice exam - untimed, open-note, and free to use any resource. Just make sure to do this on your own, and adhere to the course AI policy. As a reminder, you'll be able to fix your mistakes for 50% of the points back after your exam is graded.
2.  [**Check-Out : Exit Survey**](https://docs.google.com/forms/d/e/1FAIpQLSeQ-Q5rcOgbvwUjU6T6zcdekouxpQgd9YyEtqnLeNNw6ri9BA/viewform?usp=sharing&ouid=116640489076056213151). A few final short exit survey questions about how the summer class went, and a few questions to help guide our Fall class.

### Helpful Resources

- [**More on using jtools**](https://www.loom.com/share/2e1c7bcea5fe4a719935fa38442f2d55)**.** A video walking through how to use jtools in R to create summary regression tables. Note : there was an error in uploading the video...I have a ticket with Loom to try and fix the error. Let me know if doesn't end up working and I can re-record if needed!
