---
title: "COMPSS 202 - Introduction to Applied Statistics"
format: html
editor: visual
---

### Summer 2026

**Lectures (3 Units) \|** Asyncrhonous weekly; posted Mondays at 12:00 AM Pacific Time.

**Professor \| Arman Catterson, PhD \[he / his / او \]** 🐱. Drop-in office hours are held on Zoom Mondays, 1:00 PM - 2:00 PM Pacific Time and Thursdays 9:00 PM - 10:00 PM Pacific Time. You can also schedule individual meetings in office hours here (see bCourses for links to zoom room and scheduling). If these times don’t work, reach out via e-mail and let me know your availability (and the question you have) and we can find a time!

**Reader \|** Nathalie Fernandez (nfe\@berkeley.edu). Drop-in office hours are Mondays, 9:00 PM - 10:00 PM Pacific Time and Thursdays 1:30 PM -  2:30 PM Pacific Time (on Zoom). Sign-up here for individual appointments. \[See bCourses for link\]

**Course Description \|** Statistical analysis is the backbone of applied scientific thought, and it also features prominently in business and policy, both historically and today. This course aims to help bring all entering MaCSS students up to the required level of proficiency in applied statistics to be successful in their coursework and future careers. Students will develop the statistical intuition and analytical techniques to achieve proficiency in programming in R with Jupyter notebooks and with RStudio, univariate statistics, measurement reliability and validity, sampling and inference, hypothesis testing, and linear regression.

**Textbooks \|** We’ll be drawing from [Why Statistics (WS)](https://catterson.github.io/ystats/) - an open-source textbook that is integrated with this course to provide an overview of the statistics and R programming needed for this course, with optional reading from [Learning Statistics With R (LSR)](https://learningstatisticswithr.com/) and other supplemental sources. If you come across a reading or website that you find helpful, please share it with me and others!

##  Course Outline

+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
|          |                                                                   |                    |                                                                                           |
+==========+===================================================================+====================+===========================================================================================+
| **Date** | **Topic**                                                         | **Readings**       | **Assessments (due Sunday 11:59 PM PT)**                                                  |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 6/22     | [**1 \| Variables**](/COMPSS202/1_WelcomeMaCSS.qmd)               | WS : Intro         | [Lab 1 (Defining Variables)](/COMPSS202/Labs/Lab1.qmd) & Quiz 1 (Vocabulary (on bCourses) |
|          |                                                                   |                    |                                                                                           |
|          | in R : load R; define a variable in R; write a script.            | WS : Ch 1          |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : evaluate variation and purpose of stats              |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 6/29     | [**2 \| Data**](/COMPSS202/2_DataMaCSS.qmd)                       | WS : Ch 2          | [Lab 2 (Onboarding Data)](/COMPSS202/Labs/Lab2.qmd)& Quiz 2 (Loading Data)                |
|          |                                                                   |                    |                                                                                           |
|          | in R : load & navigate data; work with Quarto.                    |                    |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : learn from a graph without statistics                |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 7/6      | [**3 \| Description**](/COMPSS202/3_DescribeMaCSS.qmd)            | WS : Ch 3          | [Lab 3 (Happiness Data)](/COMPSS202/Labs/Lab3.qmd)& Quiz 3 (Descriptive Stats)            |
|          |                                                                   |                    |                                                                                           |
|          | in R : summarize data & remove outliers.                          | WS : Ch 4          |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : apply statistics to distributions                    |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 7/13     | [**4 \| Models, Part 1**](/COMPSS202/4_PredictMaCSS.qmd)          | WS : Ch 6          | [Lab 4 (Twitter Emotion Data)](/COMPSS202/Labs/Lab4.qmd) + Quiz 4 (Models)                |
|          |                                                                   |                    |                                                                                           |
|          | in R : define and interpret a linear model                        |                    |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : apply a model to your life                           |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 7/20     | [**5 \| Models, Part 2**](/COMPSS202/5_CategoricallyMaCSS.qmd)    | WS : Ch 7          | [Lab 5 (COVID Health Data)](/COMPSS202/Labs/Lab5.qmd)+ Quiz 5 (Models Again)              |
|          |                                                                   |                    |                                                                                           |
|          | in R : define a model when the IV is categorical                  |                    |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : interpret the model; releveling.                     |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 7/27     | [**6 \| Sampling Error**](/COMPSS202/6_MaCSSErrors.qmd)           | WS : Ch 8          | [Lab 6 (Narcissism Data)](/COMPSS202/Labs/Lab6.qmd) + Quiz 6 (NHST Analysis)              |
|          |                                                                   |                    |                                                                                           |
|          | in R : estimate sampling error                                    | LSR : Ch15.5       |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : interpret NHST output 🙂                             |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 8/3      | [**7 \| Model Evaluation and Recap**](/COMPSS202/7_MaCSSEval.qmd) | WS : Ch 9          | [Lab 7 (Practice Exam)](/COMPSS202/Labs/Lab7.qmd)                                         |
|          |                                                                   |                    |                                                                                           |
|          | in R : compare and evaluate model quality                         |                    |                                                                                           |
|          |                                                                   |                    |                                                                                           |
|          | with brain : recap                                                |                    |                                                                                           |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+
| 8/10     | [**8 \| Conclusion**](/COMPSS202/8_AssessMaCSS.qmd)               | Quarto Tutorial    | Exam                                                                                      |
|          |                                                                   |                    |                                                                                           |
|          |                                                                   |                    | Exam Revisions due 8/18 by 11:59 PM PT                                                    |
+----------+-------------------------------------------------------------------+--------------------+-------------------------------------------------------------------------------------------+

## **Grade Details**

Your grade in the class will be based on the following components.

|                   |                     |                         |
|:-----------------:|:-------------------:|:-----------------------:|
| 30% Participation | 40% Lab Assignments | 30% Article Discussions |

**Letter grades will be based on the following cutoffs :**

+---------------+---------------+----------------+--------------------------+
|               |               |                |                          |
+:=============:+:=============:+:==============:+:========================:+
| A+ is \> 96.5 | B+ is \> 86.5 | C + is \> 76.5 | D is \> 59.5             |
|               |               |                |                          |
| A is \> 92.5  | B is \> 82.5  | C is \> 72.5   | F is \< 59.5             |
|               |               |                |                          |
| A- is \> 89.5 | B- is \> 79.5 | C- is \> 69.5  | note : an 89.499 is a B+ |
+---------------+---------------+----------------+--------------------------+

## About This Class

Read the tabs below for more information about our class. Let me know if you have any questions or spot errors.

::: panel-tabset
#### Course Components.

**Participation.** Because we all learn from each other, your voice is needed! Participation grades will be based on in-person attendance, completion of check-ins throughout lecture, and engagement in class activities and discussion. You may miss up to one lecture with no penalty. Lectures will be recorded for students who want to review the material they missed (however watching the recording does not count toward your participation grade.)

**Article Discussion.** Each week, we will discuss one article related to the course topic. All students should plan to read the article, and post comments to a discussion forum on bCourses.

**Lab Assignments :** Each week, you will work through a “lab” assignment that is designed to help practice the skills we review in lecture and readings. You can expect to work on these in lecture, in discussion sections, and at home as needed. Each lab document will have a set of questions to answer - you should submit answers to these questions as a separate document to bCourses. Lab assignments are due the week after they are assigned. You can drop your lowest submitted lab assignment.

**Final Project (Research Paper) :** You’ll apply the skills you have learned in the class to propose a novel research study that includes both survey and experimental methods that addresses a research question relevant to your interests. There will be several milestones to support this assignment. See the Final Project Description & Rubric for more information.

**Extra Credit :** There will be no extra credit offered in this course, even for students who ask kindly.

#### Course Policies.

**Late Work Policy.** Assignments and Discussion Posts are due before lecture, the week after they are assigned. Late assignments will be penalized 25% for any reason (even if they are 1-minute late), and 50% if turned in more than a week late (after the key has been posted). Students with extra time DSP accommodations should work out a plan to submit work within a week of the original deadline.

**Computer Access.** Access to a personal computer is required We will spend time each lecture working in R - a free and powerful statistics program that works with all operating systems and computers. Laptops are available for rent from the library (see [Berkeley’s Technology Loan Program](https://studenttech.berkeley.edu/devicelending)), or you can purchase one that will work for this class for as little as \$150 (less than the price of most textbooks, which is not required for this class). Talk to me or a GSI if access to a laptop or computer is interfering with your ability to do well in the course.

**Regrades.** Students may ask for a re-grade on exams and papers if they believe they lost points for something they should have earned. To request a regrade, talk to your GSI in office hours or set up a meeting. In the case that you and your GSI cannot resolve the regrade issue, the professor will step in and regrade the exam. For final project regrades, just e-mail the professor. When requesting a regrade, you consent to have your score increased or decreased if we find that you earned points you should not have earned.

**Student Contact.** It is your responsibility to regularly check e-mail for announcements. Please post questions about the class or R to our class discord page, so other students can see the question (and answer) and benefit from your question! If you have specific questions to e-mail me, please make sure to (a) search the syllabus and / or Google for the answer to your question and (b) contact your TA about your question. I am always happy to answer any questions in office hours (either during the scheduled time or online by appointment), or before, during, or after lecture. I should respond to e-mail within 24 hours on weekdays (I do not check e-mail on weekends); please send a gentle reminder if I do not respond in this timeframe. Thanks!

**Incomplete Policy.** I will only grant an incomplete to students who (1) have a significant life event that prevents them from completing the final project at the end of the semester and (2) are passing the class at the point they request the incomplete.

**Academic Integrity**. Do NOT cheat. Do NOT plagiarize. To copy text or ideas from another source (including your own submitted coursework) without appropriate reference is plagiarism. You may work on lab assignments with other students, but should be able to understand what you are doing. You may not work with other students on the R exam. Anyone caught cheating or plagiarizing will receive a zero on the assignment or test, and **will** be reported to the Office of Student Conduct. It is your responsibility to read the official Student Conduct Policy for more information about campus standards and policies regarding Academic Integrity.

**AI Policy.** Generative AI tools should be used to support - not replace - your learning. All students must disclose how they used generative-AI software for each assignment (writing, coding, troubleshooting, etc.). If you used AI tools in any way (e.g., idea generation, writing, editing, troubleshooting or generating R code, etc.) you must include an appendix at the end of the assignment where you include screenshots of your specific queries and answers. Failure to be transparent about the use of AI tools - or feeding an assignment into an AI tool and using the output to completely replace your own work - will result in a zero of the assignment and a scheduled meeting in office hours. Multiple violations of this policy will result in the professor submitting a report to the Academic Integrity office and an F in the class. This is a new technology that we are all figuring out, so ask me if you have questions about this policy, or want to chat more about ways to use (or not use) AI in this class. I ultimately want to see that you are learning the material, and that any AI tools that you use are helping YOU learn, and not replacing the learning process. Whew!!

**Respect for Others.** We **all** belong in our classroom, and I hope that everyone feels free and supported to express our identities when relevant. To achieve this goal, make sure that you are treating others with respect in this course. This means considering others’ opinions and perspectives, making sure not to generalize to groups (or ask students to be representatives of their group), and being mindful of the words that you use. (Also remember that nothing is ever really deleted from the internet, so please be extra mindful of the words you use.) While I will be monitoring class posts and communication, feel free to reach out to me if you see another student engaging in disrespectful or threatening behavior. Of course, this extends to me as well - if you feel like there are parts of the course instruction, subject matter, or class environment that create barriers to your success or inclusion, please contact me via e-mail and trust that your voice will be heard and I will not punish you for offering constructive criticisms of my teaching. I’m very open to learning how to be a better teacher, and always learn a lot from my students. 

**Sensitive Subjects.** Our class will touch on important and potentially sensitive topics that are related to social science and data, such as racism, depression, sex, and poverty. These topics can generate strong emotional responses in students for a variety of reasons - such as their own past histories with these topics or their reactions to the ways the information is presented or described. I will try to make sure to give you a heads up when we start to discuss these topics so you can be mindful of your reactions.

**Strategies for success**. Do your readings, complete assignments on time, understand how the topics and information relate to what you’ve learned (and are learning), and if you don’t understand something, please ask the question!

**Most important.** Please let me know as soon as there is anything going on in your life that you think may affect your ability to do as well as you would like in this class (e.g. sickness, work, small children at home, threats to immigration status, etc.), and I will do my best to work with you on a plan to succeed in the class. If you're not comfortable talking to me directly, you can talk to your TA who can talk to me about your issue.

#### Student Support Services.

UC Berkeley offers a variety of services to help support students facing difficulties in these historic times.

**Students with Disabilities :** Students who require support or adaptive equipment because of a specific disability -- or would like to be tested to see if they qualify for a learning, auditory, or visual disability -- can request these services through the Disabled Students Program (DSP) office. Please note that I can only provide accommodations authorized by the DSP office. If you have DSP status, make sure you submit your letter and feel free to talk to me or a GSI about any specific accommodations you need, or other ways we might be able to make the class more accessible. \[260 César E. Chávez Student Center\| 510-642-0518 \| <https://dsp.berkeley.edu/>\]

**Students with Mental Health Issues :** If you feel a mental health issue (e.g., depression, anxiety) is negatively impacting your ability to succeed, I’d highly encourage you to seek out experts who can help. Berkeley has several free, confidential, and science-based programs designed to help students. \[<https://uhs.berkeley.edu/caps> \| Tang Center 3rd Floor \| 510-642-9494 \| After hours support line : 855-817-5667\]

**Undocumented Students :** I believe that all people deserve equal access to education. The UC Berkeley Undocumented Student Program has organized resources to support undocumented students, protect their rights, and offer potential financial aid \| <https://undocu.berkeley.edu/>

**Students from Low-Income Backgrounds :** The Extended Opportunity Program (EOP) provides college support services for low-income students. Services include additional counseling, financial assistance (study-time parent grants, work-study assignments, and book vouchers), child-care opportunities, and assistance transferring to four-year colleges. \[119 César E. Chavez Student Center \| 510-642-7224 \| <https://eop.berkeley.edu/>\]

**Free On-Campus Tutoring :**

- **The[Data Peer Consulting program](http://bit.ly/data-peer-consulting) in the Division of Computing, Data Science, and Society.** This program strives to help make data science accessible across the broader campus community, by aiming to help undergraduate students, graduate students, staff, and faculty with research project infrastructure or other projects and modules that incorporate data. 

- **The UC Berkeley [D-Lab](http://dlab.berkeley.edu/services)**. Drop-in consulting where people may be able to help you with R specific problems.

- [**Librarians are great**](http://www.lib.berkeley.edu/help/research-help). They can help you find research articles for your final project, think about how to organize or structure your literature review, and probably have other powers from a life of being surrounded by books.
:::
