---
title: ""
format: html
editor: visual
---

# Week 10 (No Class, But The Learning Continues)

## Announcements.

Hi class. Thank you for reading these words that I wrote. Does it sound like me? Can you make the voice sound like someone else? Amazing.

Anyway, hope y'all are enjoying the week off. Before next week, please complete the following.

1.  [**Complete this Check-In**](https://docs.google.com/forms/d/e/1FAIpQLSfifGNo6p7xNlhRAjFePIuUBwMJ6zzYSQ77hKNqJYi5qte8SQ/viewform?usp=header). Your thoughts on the R Exam and rest of the semester.
2.  **Watch the two videos below.** (Or just the first video would probably be fine.)
3.  **Read Chapter 8 and take the Reading Quiz.** We back.

## Class Videos

In the next part of our class, we'll discuss how scientists use information from the individuals they studied to make a prediction about what EVERYONE is like. This can be confusing, because scientists are just making up data to guess about what people they did not study are like, and often do so in confusing and misleading ways. But the good news is doing this in R is very easy, and you will learn, and we will review in class.

#### The Problem of Sampling and NHST \[20 min\]

Focus on the difference between making predictions from our sample and the population, the difference between sampling error and bias, and get a quick(ish) overview of one (confusing) way we try to estimate sampling error called Null Hypothesis Significance Testing (NHST). The p-value and "significance" stuff you may remember from another stats class.

{{< video https://youtu.be/HDWYz5ror4o >}}

#### More on Sampling Error \[12 min\]

A 12-minute video focusing more on “sampling error” if you are interested, why researchers should care about it, and how it can be reduced.

{{< video https://youtu.be/fp1xsBMSBg0 >}}
