---
title: "Week 7 - Chapter 6"
format: html
editor: visual
---

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
- **Office Hours :** normal schedule this week.
- **Lab Grades Updated :** thanks for your patience!
- **Brain Exam Grades Soon :** whoop.
:::

::: {.column width="50%"}
- **8:55 - 9:20.** Check-In and Review
- **9:20 - 10:00.** Linear Models Review
- **10:00 - 10:10.** BREAK TIME
- **10:10 - 11:00.** Working on Lab 5
:::
:::::
::::::

### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/dvcstats/slides/ch6_slides.html" width="100%" height="500px" title=""></iframe>
```

- **CHECK-IN : [Working with the World](https://docs.google.com/forms/d/e/1FAIpQLSe-830Xaq_jAfRomviIR6CrIaurGYB_hUJcRYbLFXQfeASI4A/viewform?usp=header)**
- **DATA (AND CODEBOOK) FOR TODAY : [Mini Class](https://www.dropbox.com/scl/fo/5gzf195h8r3n8kh05miym/AKkVJKMDik5gM600FBPk_Yc?rlkey=acd199vikc6um4ufl0g9595od&dl=0)**
- **Professor R Scripts \[[Zoom Room](https://www.dropbox.com/scl/fo/ofchakmk3d1ep17u2r5r5/APTz8gRoQo9AHhw2XPY5TZs?rlkey=mdept9ym448grm4vya184bbrd&dl=0) + [Room Crew](https://www.dropbox.com/scl/fo/fa4okobq89jhhj0wthgy5/AHJsWr-fakA7N8JnlLZHKIs?rlkey=hfw992f7lj8nzfbcz6qp7n2og&dl=0)\]**

### For Next Week

- **Complete [Lab 5](/dvcstats/labs/Lab5.html)**

- **OPTIONAL : Prepare to Learn about Using Quarto.** Next week, we will try to use Quarto to create a document. I demoed this at the end of class, but below are some resources if you want to get a head start on the learning. Note : these resources go more in-depth than we will!

  - [**Video : Introduction to Quarto**](https://www.youtube.com/watch?v=_f3latmOhew)**.** The best intro I could find...too complicated for much of what we will do, but gives you a sense of what is going on with Quarto. We will review (and keep it SIMPLE) in class next week.

  - [**Website : Quarto Documentation**](https://quarto.org/)**.** The quarto website has some pretty good documentation. I often have this open when writing the textbook / doing stuff in Quarto.

- **OPTIONAL : Learn about the Implicit Attitudes Test.** Next week, we'll work with a dataset that measures "Implicit" or "Unconscious" attitudes about racism. Thought it might be nice to preview this measure, since it can be confusing.

  - [**Take an IAT**](https://implicit.harvard.edu/implicit/takeatest.html)**.** If you are interested.

  - [**Watch a short video on the IAT**](https://www.youtube.com/watch?v=EOPbf3Ponew)**.** Maybe take the test first before watching the video?
