---
title: ""
format: html
editor: visual
---

# Week 2 - Monday, March 16th

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
**Welcome! We will get started soon. In the meantime, please complete the following :**

-   **Check-In :** still graded for completion; a warmup.
-   **Lab 1 Key Posted :** will discuss!
:::

::: {.column width="50%"}
-   **10:10 - 11:30.** Check-In and Review (Linear Models)
-   **11:30 - 11:45.** Break Time
-   **11:45 - 1:00.** Objectivity Armoring and Likert Scales
:::
:::::
::::::

### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/macssstats/slides/2_modelscales.html" width="100%" height="500px" title=""></iframe>
```

-   [**Check-In**](https://docs.google.com/forms/d/e/1FAIpQLSdUuPUWN5_lkHw8DkudwT0--qu8eEFurLSYeJ227V37LC3g1A/viewform?usp=header) **:** Use R to DESCRIBE, PREDICT, evaluate ERROR, and think about how you might use the knowledge to CONTROL OUTCOMES!
    -   [**the hormone dataset and codebook**](https://www.dropbox.com/scl/fo/2f7kaifml4sq8mq1c7dfi/ALPLJarvk4vomfrddx2Buyg?rlkey=i62g4s3nzeldyvvffgviolobi&dl=0)**.** from a study of business students at Berkeley.
-   [**Professor Notes**](https://www.dropbox.com/scl/fo/1g76jzayvff4kwaldyn52/AOfNP20yVujSO5akd1U0k98?rlkey=1xs6rqsgdoj8pgls1efbawl7i&dl=0). My R scripts and other notes, saved in real-time.
-   [**VISION BOARD**](https://docs.google.com/spreadsheets/d/11FZJ76JMBUkKYZRoWASrHhPIldmP7Pziz-WGnlIZuC4/edit?usp=sharing). Where we will share work we do in class.

### Additional Reading and Support Materials

-   **need a review of stats and R?** below are some relevant links from the stats textbook I use with my introductory classes. let me know if these are useful / you have ideas to make more useful :)

    -   [**chapter 6 :**](https://catterson.github.io/ystats/chapters/6R_LinearModels.html) on the linear model with a numeric IV and numeric DV

    -   [**chapter 7 :**](https://catterson.github.io/ystats/chapters/7R_CategoricalIV.html) on the linear model with a categorical IV and numeric DV

    -   [**chapter 9 :**](https://catterson.github.io/ystats/chapters/9R_ModelExtensions.html) on the linear model when your categorical IV has more than two levels

# For Next Class.

## No Article Discussion. Will discuss objectivity interrogations next class :)

-   ~~**Read This Article.** Chung, J. M., Meijer, L., Zonneveld, R., Al Sawaf, Z., Alajak, K., Moopen, N., ... & Laceulle, O. M. (2022). Lessons learned from conducting a study of emotions and positive personality change in Syrian origin young adults who have recently resettled in the Netherlands. European Journal of Personality, 36(4), 665-682.~~

-   [~~**Submit Your Response Here**~~](https://docs.google.com/forms/d/e/1FAIpQLSdGkCcxV80BCkshlZwLNomMMsZOxmOnvGjrdC1Z6w9YEnLltg/viewform?usp=publish-editor)~~. We'll use these responses to guide our discussion of the article next week. Great to use your own voice; don't worry about sounding smart or having "perfect" english!~~

## Lab 2. Onboarding Problems

**Use [the Onboarding Dataset](https://www.dropbox.com/scl/fo/ln7vo5wta8u06mq0ha719/ADvvtqcFzK0TnvUQTtL-2U4?rlkey=h4johl6nr6ht451ci3ad8yv7v&dl=0) (from Week 1) to prepare a report that uses the data to a) practice working with linear models, b) learn something about our class, and c) practice thinking about how we might use this knowledge.**

1.  Define three separate linear models to predict [one numeric variable]{.underline} from the dataset (a "dependent variable" or DV) from (A) a numeric variable (Independent Variable 1 = IV1), (B) a different numeric variable (IV2) and (C) a categorical variable (IV3). For each model, make sure to include a graph, and report the slope, intercept, and $R^2$ term. *Note : each linear model should use the same DV, and this DV should be numeric.* *There's no need to report the p-values yet :) but you can include these if you want.*
2.  Below your graphs and statistics, explain (A) what you learn from each model, (B) why you might find this pattern in the data, (C) what other questions you might have about these data / ideas you have to improve predictions, and (D) how we might use this knowledge. No R is required for this - just your human brain.
3.  Organize this report as a 1-2 page document. Think about what information your audience might need to understand your data and interpretation. We will look at some of these in-class together, so be prepared to share your work with the class!
