---
title: ""
format: html
editor: visual
navbar: false
---

## Week 8 - Wednesday, March 18th

### Class Goals

1.  Review understanding predictive statistics (patterns in the data) and evaluate the Big Five and Myers-Briggs personality measures.
2.  Look over some Dig Deeper projects and examples.
3.  Students all learning; Professor not rushing; we all enriched and nourished by knowledge of research methods.

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
-   **Spring Break Next Week.** Hooray.
-   **Um.** Yeah.
:::

::: {.column width="50%"}
-   **11:10 - 11:50.** Check-In and Review (Personality).
-   **11:50 - 12:10.** Defining a Likert Scale.
-   **12:10 - 12:35.** Dig Deeper (Discussion 7)
:::
:::::
::::::

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/8_patterns.html" width="100%" height="500px" title="" border="5px"></iframe>
```

### Useful Links

-   [CHECK-IN : valid, reliable, and biased personality](https://forms.gle/g2Mfxiobu7qW1BgW9)
-   [Dig Deeper Assignment](/rm/notes/digdeeper.qmd)
-   [Vision Board](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)
-   [Personality Profile](/rm/readings/Personality.qmd) \[making time\]

## Before Next Class

### Readings for Next Week (and our Quiz)

1.  [**Review / Scan / Ignore the Textbook Chapter on Correlations**](https://kpu.pressbooks.pub/psychmethods4e/chapter/correlational-research/)**.** They are patterns in the data.
2.  **Review the [Meyer et al. (2001) article](https://www.dropbox.com/s/r0uwvdqezzvlvdb/2001_Meyer_EffectSizes.pdf?dl=0) on effect sizes.** You do not need to read all of this article, and promised me you would not in class! [**Here’s a video professor recorded**](https://www.loom.com/share/3228d91e431e4be4b3f1c871df7f1db3?sid=0f022c43-6667-447e-b63c-7be544e9643b) in a previous semester walking through how to navigate this article to answer some similar questions I'm asking this semester. (I cut a few steps (and hadn't yet seen the light of the vision board....), but this should give you the general idea.)
3.  [**Four Reasons Why Patterns Occur in the Data \[10-minutes\]**](https://youtu.be/2plZk2tQIQ8)**.** These apply to most situations, and will be good to know!

### Week 8 Discussion Questions.

**All work goes in the Vision Board! I will update the gradebook based on what you submit in the vision board.** **No need to post in two separate places! Hooray, professor is learning!!!**

1.  **Look through the result section from your DIG DEEPER (scientific research) article.** Paste a screenshot of one part of the RESULTS section that seems like it might be relevant to the main "headline" of the article (or pop psych article). Does this make sense at all to you? Did they report the result as a regression / correlation / slope, or use some other metric? Okay if you are confused! We will START our next class (after the check-in) looking over these. [Here's a video I recorded where I went through my example (and also got confused!)](https://www.loom.com/share/b03c1c1b19964c98ba074d2e120ece8d)
2.  **Now, review the Meyer et al. (2001) article on effect sizes.** Identify a relationship from Table 1 or Table 2 that you think is interesting / have heard about in other classes. Write this relationship out as a model.
3.  **Report the correlation coefficient (from the table) for this relationship.** Use the “[correlation visualizer](https://rpsychologist.com/correlation/)” to illustrate what this relationship might look like (no screenshot needed, but look this up to get practice internalizing what a correlation looks like). Reflect. does this seem like a strong or weak relationship to you? What other factors might explain this relationship?
4.  **REPLY TO ANOTHER PERSON :** Apply the “four reasons” framework to evaluate why their relationship might occur.

I've posted an example in the Week 8 Vision Board to help get y'all started.
