---
title: ""
format: html
editor: visual
navbar: false
---

## Week 13 - Wednesday, May 13th

### Class Objectives

1.  30 MIN : Interaction Effect & Milestone 2 Review
2.  45 MIN : Introductions to Introductions
3.  15 MIN : Hey It's a Poster!!!

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/13_IntroPoster.html" width=100% height="400px"></iframe>
```

### Useful Links

-   [**CHECK-IN : More Interaction Effects**](https://forms.gle/fseShMoUUiewVcHb7)
    -   Study A : Cohen, S., Tyrrell, D. A., & Smith, A. P. (1991). Psychological stress and susceptibility to the common cold. New England journal of medicine, 325(9), 606-612.
    -   Study B : Hoffman, M., Gneezy, U., & List, J. A. (2011). Nurture affects gender differences in spatial abilities. Proceedings of the National Academy of Sciences, 108(36), 14786-14788.
-   [**Final Project Description & Rubric**](https://docs.google.com/document/d/1QJKm9s8WUXAoYACf_pC9QIWdYyfEOHQNMnP4unkXGYI/edit?usp=sharing)
-   [**Vision Board**](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)

### Would You Like To Learn More

-   [**Collection of all the posters that I passed around.**](https://www.dropbox.com/scl/fi/3ieqzi1qc3xmu719jmehu/Poster_Examples_RF.pdf?rlkey=1hh1qzarepidni0affnst6ps5&dl=0) DO NOT READ ALL OF THESE. Useful just to get a sense of the genre.

## Before Next Class : Milestone #3

-   Outline your introduction (what past research has been done on your topic and why is your study needed?)

-   Write a short blurb for how you would measure or manipulate the variables in your model (why should we trust these measures?)

-   Look over the poster example(s)
