---
title: ""
format: html
editor: visual
navbar: false
---

## Week 7 - Wednesday, March 11th

### Class Goals

1.  Learn how to define and evaluate the quality of a likert scale.
2.  Review descriptive statistics, and think about predictive statistics.
3.  Students all learning; Professor not rushing; we all enriched and nourished by knowledge of research methods.

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
-   **Spring Break in Two Weeks.** Hooray.
-   **Fill out the professor evaluation.** Please and thank you \<3
:::

::: {.column width="50%"}
-   **11:10 - 11:50.** Check-In and Review (Personality).
-   **11:50 - 12:10.** Defining a Likert Scale.
-   **12:10 - 12:35.** Dig Deeper (Discussion 7)
:::
:::::
::::::

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/7_surveys.html" width="100%" height="500px" title="" border="5px"></iframe>
```

### Useful Links

-   [**Check-In Here : tinyurl.com/prepattern**](https://docs.google.com/forms/d/e/1FAIpQLSdzuU9IKFyElROMwkgkZgGj_3DuXxIKzot5kjkEu2QXpI7S5g/viewform?usp=header)
-   [Dig Deeper Assignment](/rm/notes/digdeeper.qmd)
-   [Vision Board](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)
-   [Personality Profile](/rm/readings/Personality.qmd) \[if time\]

### Due Next Week before Class

1.  **Read the articles below and use these to complete Discussion 6**. Post answers to Questions 3 and 4 on the Vision Board, but also submit ALL answers to the Canvas assignment (not a discussion post; the Vision Board will do this work). *Sorry this is confusing and maybe redundant thanks for your patience and participation on this journey.*
2.  **Take two personality surveys (for Quiz 6).** No multiple choice questions this week. Instead, Quiz 6 contains links to two different personality surveys that you should take. Save your responses for each survey and submit your responses to the anonymous Google Form. At the end of the Google Form, you'll get a secret code to submit for the Quiz (this ensures that the data will be anonymous.)

### Readings for Next Week (and Quiz 6)

1.  [**Reading on Likert Scales**](/rm/readings/LikertScales.qmd)**.** Likert scales are one of the most common ways researchers measure people, are foundational to much of psychology (even some fMRI research depends on them), and we will learn about them and how to critically evaluate them. Heads up - Likert is *technically* pronounced "Lick-ert" but nobody really says that because it sounds gross...everyone just calls it "Like-ert". But if someone tells you it's actually "Lick-ert" now you won't be surprised and can be like, "yeah, I know but that sounds gross and nobody says that" or you can say it "Lick-ert" and reject the social influence bias.

2.  [**More on Constructing Surveys**](https://kpu.pressbooks.pub/psychmethods4e/chapter/constructing-surveys/). You can skim much of this, but focus on a) context effects and item-order effects on survey responses, b) the BRUSO model of effective items, c) whether these authors tell you to say "Lick-ert" or "Like-ert".

3.  [**The McAdams Life Narrative Interview**](https://www.dropbox.com/s/n7s7jk3wutdeflx/McAdams_Narrative_Instructions.pdf?dl=0)**.** One of my favorite methods of assessment. It's rarely used in psychology, but I think demonstrates a very rich way of thinking about persons. The whole interview takes a few hours to conduct, and leaves you with zero numbers to analyze. You don't need to do the entire interview, but let us know if you do and how it goes \<3

4.  **OPTIONAL READINGS :** For students who would like to learn more.

    -   [**A Mega List of Personality Surveys**](https://ipip.ori.org/newIndexofScaleLabels.htm)**.** We'll look at this in class next week, but here's a long list of free personality surveys for researchers to use. Note that some variables (e.g., extraversion) have many different scales written for them. Personality psychologists often get into long-winded and sometimes heated debates about how best to measure a construct.
    -   [**The Paulhus & Vazire (2007) “Handbook Chapter” on Self-Reports**](https://www.dropbox.com/s/9erlgou7mbwerpr/5_Paulhus_Vazire_2007.pdf?dl=0)**.** A handbook is basically a textbook for researchers - not original research, but a summary of what researchers think (and have learned) about a topic. Meant for graduate students and other researchers who are first learning about a topic, or perhaps a highly-motivated college students with extra time who is still reading these words!

### Week 7 Discussion Questions.

**We are going to resume working on the DIG DEEPER assignment. Hooray.**

1.  **ON THE** [VISION BOARD](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)**.**

2.  **FOR THIS ASSIGNMENT.** Copy/paste what you did on the vision board so professor can quickly grade and give feedback as needed.
