---
title: ""
format: html
editor: visual
navbar: false
---

## Week 12 - Wednesday, May 6th

### Class Objectives

1.  45 MIN : Introduction to Interaction Effects
2.  45 MIN : Introductions to Introductions

### Class Slides

```{=html}

<iframe data-external="1" class="slide-deck" src="/rm/slides/12_M2XEIntro.html" width=100% height="400px"></iframe>
```

### Useful Links

- [**CHECK-IN (Resume Study)**](#0) **:** **tinyurl.com/finalprojectyep**
- Bertrand, M., & Mullainathan, S. (2004). Are Emily and Greg more employable than Lakisha and Jamal? A field experiment on labor market discrimination. *American economic review*, *94*(4), 991-1013. \[[LINK TO ARTICLE](https://users.ssc.wisc.edu/~gwallace/Papers/Bertrand%20&%20Mullainathan%20(2004).pdf)\]
- [Final Project Description & Rubric](https://docs.google.com/document/d/1QJKm9s8WUXAoYACf_pC9QIWdYyfEOHQNMnP4unkXGYI/edit?usp=sharing)
- [Vision Board](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)

### Would You Like To Learn More?

- [**Prof. Chapter on Interaction Effects.**](https://catterson.github.io/ystats/chapters/11R_InteractionFX.html) Can skip the stats stuff and just focus on the interpretation of the graphs.

## Before Next Class : Milestone #2

Sketch out a graph of your interaction effect, and paste it to the vision board. See the video below on how to do this using a computer *(note : to insert your graph on the vision board take a screenshot and paste it, since copy/paste does not work.)*

-   [**Milestone #2 Template**](https://docs.google.com/spreadsheets/d/1VrEm0QPVdTzFjX7K9GAkjWD_QRXrpnl0iPy26aqYky4/edit?usp=sharing)
-   [**Professor Video Walking Through The Template Here**](https://www.loom.com/share/85d9b902b3e74aef90ff649f50f16015)