---
title: ""
format: html
editor: visual
navbar: false
---

## Week 1 - Thursday, August 27th

### [Return to Class Page](https://catterson.github.io/rm/RMDVC.html)

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/1_knowscience.html" width=100% height="400px"></iframe>
```

### Check-In : [tinyurl.com/helloRM](tinyurl.com/helloRM)

- Type this url into your browser or phone \^\^

- Or : find these notes on Canvas (under Class Page) and click the link.

### Agenda and Announcements {.smaller}

::::: columns
::: {.column width="50%"}
**Agenda :**

- 10 Min : Welcome and Check-In
- 30 Min : Part 1 : Research in Psychology
- 30 Min : Part 2 : Sources of Knowledge
- 10 Min : Recap & Next Week
:::

::: {.column width="50%"}
**Announcements :**

- *These notes are on Canvas*. Let me know how access goes.

- *Waitlist students!* Talk to me after class.

- *Office Hours in SSSC.* 12:35 - 1:35. Across the street.
:::
:::::

### Due Next Week before Class

1.  Read the articles below.
2.  Complete Discussion 1 (Questions below, submit on Canvas).
3.  Complete Reading Quiz 1 (on Canvas).

### Week 1 Readings

1.  [**Epistemology (Methods of Knowing).**](https://opentext.wsu.edu/carriecuttler/chapter/methods-of-knowing/)From your unofficial textbook, a list of five different methods of knowing : intuition, authority, rationalism, empiricism, and the scientific method. When reading, practice re-explaining the term in your own words, using the examples to guide you, and trying to connect to your own real-life examples.
2.  [**The Scientific Method in Five Easy Steps**](https://catterson.github.io/ystats/chapters/1R_WhyStats.html#part-3-how-science)**.** It is the same thing you did in science fair, but with more math. A quick overview, with some deeper thoughts about how to develop a research question that you care about. Please also [read the section on "MeSearch" in Part 2](https://catterson.github.io/ystats/chapters/1R_WhyStats.html#critical-and-culture-in-statistics) (but you can skip the other stuff.)
3.  [**The Replication Crisis in Psychology**](https://nobaproject.com/modules/the-replication-crisis-in-psychology)**.** Focus on the definition of a replication, the reasons for non-replications, and some of the potential solutions to the problem.
4.  **OPTIONAL READINGS :** for those who would like to learn more. Let me know if you find other cool readings on these topics to add.
    - [**More on the replication crisis in psychology**](https://www.vox.com/future-perfect/21504366/science-replication-crisis-peer-review-statistics). The article is now behind a paywall...but [here's a PDF of the article from the Internet Archive](https://www.dropbox.com/scl/fi/21h3kcq6kc5jszo00fm6w/1_Vox_ReplicationCrisis_2020.pdf?rlkey=qzf44rviccwt2ucwvpo86p8ie&dl=0).

### Week 1 Discussion (submit to Vision Board, Week 1 Tab)

**YOUR POST :** Use the readings to answer the following questions. Answer these questions on the Vision Board for Week 1. There's no word count requirement, and it's good to be concise.

1.  **Epistemology in our Beliefs.** Focus on the belief you wrote about during class (or choose a new belief). Come up with examples of how INTUITION, AUTHORITY, RATIONALISM, and EMPIRICISM would inform this belief. Say the word Epistemology outloud, and see if you can fit it into a sentence this week :)

2.  **Research in Science.** Think about the research question you identified in class. What past experiences influenced your choice of this topic? How could you (or others) use knowledge of this topic in some way to change people's experience?

3.  **How Did this Make You Feel?** Reflect on the replication crisis in Psychology...what are your thoughts on this? Had you heard about this before? What is at least one other question you have about replication?

4.  **Other Questions.** Write out any other questions you might have about the reading or what we covered in Week 1.

**REPLY TO ANOTHER STUDENT'S POST :** Choose another person in the class who doesn't already have a reply.

- Write your name.

- Say hello and connect with their research question in some way (e.g., what is your own personal connection to the student's research topic? Do you think your personal experiences might influence the way you study this topic?)

- List at least one other way the student might be able to use this knowledge (for good or for bad purposes)?
