---
title: ""
format: html
editor: visual
navbar: false
---

## Week 10 - Wednesday, April 15th

### Class Goals

1.  Review the Dig Deeper participants (and overall project)
2.  Discuss Sampling Bias and Error
3.  Students all learning; Professor not rushing; we all enriched and nourished by knowledge of research methods.

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
-   **Welcome Back.** How was your week?
-   **Dig Deeper Assignment.** We gonna wrap this up today whew.
:::

::: {.column width="50%"}
-   **11:10 - 11:50.** Check-In and Dig Deeper Review.
-   **11:50 - 12:35.** Experimental Methods.
:::
:::::
::::::

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/10_samplebias.html" width="100%" height="500px" title="" border="5px"></iframe>
```

### Useful Links

-   [**CHECK-IN : mushroom data**](https://docs.google.com/forms/d/e/1FAIpQLSdtsLSxF2GlbyTzJmdoIpn-BwxMrS0Jqi0D5pDIr832GULggw/viewform?usp=header)
-   [Dig Deeper Assignment](/rm/notes/digdeeper.qmd)
-   [Vision Board](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)

## Before Next Class

### Submit Dig Deeper Assignment

-   **compare and contrast news article to research article.**

-   **include at least one detail from each section.**

-   **keep it short :**

    -   you don't want (or need) to write a lot

    -   professor doesn't have time to read a lot :(

### Gonna Keep Reading Articles

-   give next week, or now and have y'all scan / read as you have time?

-   assess scanning with discussion or vision board?
