---
title: ""
format: html
editor: visual
navbar: false
---

## Week 2 - Wednesday, February 4th

### [Return to Class Page](https://catterson.github.io/rm/RMDVC.html)

### Class Slides

```{=html}
<iframe class="slide-deck" src="/rm/slides/2_biasscience.html" width="100%" height="500px" title="" border="5px" allow="fullscreen" allowfullscreen="true"></iframe>
```

### Due Next Week before Class

1.  **Read the articles below.** Optional readings are not required; but lemme know if you read and have thoughts!
2.  **Complete Discussion 2**. Questions below, submit on Canvas.
3.  **Complete Reading Quiz 2**. on Canvas.

### Readings for Next Week (and Quiz 2)

1.  [**Research for Fun and Profit**](https://catterson.github.io/ystats/chapters/2R_Data.html#part-3-research-for-fun-and-profit)**.** A summary of scientific articles - where researchers read (and write) about the research studies. Review the publication process, types of articles, the peer review process, and different methods of evaluating a research article.
2.  **Scan the following example of peer-review in practice.** You don't need to read everything, but wanted to give y'all a flavor of what peer-review actually looks like in practice.
    -   [Here are my responses to peer-review](https://www.dropbox.com/scl/fi/gjcninkozdsnk6mcqjcpp/catterson_reviewer_response_JRP2016.docx?rlkey=3nmk8zyrjrv52qdu0k6942u9y&dl=0) from an [article I wrote](https://www.sciencedirect.com/science/article/pii/S0092656616300204?casa_token=dL2Tx9N7gbYAAAAA:ziB5qansS-6ulbZDYJGMFP4XaRvuwUEylDZfZz71ch7qQQix4UmUZhOzCCyacNGerbZqXgAaEA) that ultimately got accepted.

    -   [Here is an editor's letter in response to an article I wrote that got rejected](https://www.dropbox.com/scl/fi/irjzk85xsw0d6sprhdjzl/JPSP_power_projection_REJECT_letter.pdf?rlkey=f351q2d9lvdtkjucskxldgv9s&dl=0). The original paper was a bit of a hot mess, but I think some of their critiques also reflect some deeper problems in the field that have led to the replication crisis (e.g., "*evidence from Study 1 (with 4 samples completing just 2 items) is described as “compelling” when for some but not all samples the 2 items are positively correlated*").
3.  **Optional Readings :** Not required, but thought these might be of interest for students who were interested!
    -   **More on the Mechanisms of Scientific Publishing.**

        -   [**An Overview of the Peer-Review processes**](https://authorservices.wiley.com/Reviewers/journal-reviewers/what-is-peer-review/index.html) from an academic publisher. A few tabs on the videos you can click through to see what is required and involved.

        -   [**Scientific Journals and Articles.**](https://www.visionlearning.com/en/library/Process-of-Science/49/Understanding-Scientific-Journals-and-Articles/158) A really nicely written (I think) review of scientific articles, and how to read them.

    -   **More on the Business of Scientific Publishing.**

        -   [A much longer interview with Alexandra Elbakyan, the founder of Sci-Hub, on scientific communism.](https://www.theverge.com/2018/2/8/16985666/alexandra-elbakyan-sci-hub-open-access-science-papers-lawsuit) Here's a [PDF](https://www.dropbox.com/scl/fi/ynx4nh6vnknafqwwpuelh/2_Verge_PirateQueenSciHub.pdf?rlkey=8x3xqydy29ehkkhb4vk2q2wtg&dl=0) in case you get pay-walled.

        -   [A much longer discussion of the history of academic publishing as a big business.](https://www.theguardian.com/science/2017/jun/27/profitable-business-scientific-publishing-bad-for-science)

### Week 2 Discussion

**YOUR POST :** Use the readings to answer the following questions. Please submit answers to the graded Canvas discussion post for the grade, but when prompted please also copy / paste your work to our [Vision Board](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing) so we can more easily see this work together in class. *Prof note : let me know if this is confusing....trying something new and will see how it goes!! Trying to free our class from the tyranny of Canvas. I posted an example.*

1.  **ON VISION BOARD :** restate your research question (from Week 1, or feel free to reviese!) Then, define a linear model for the research question (and theory) that you might be interested to explore as a researcher. I posted an example in the Vision Board for y'all as a guide.

2.  **From Discussion 1 :** re-share that advertisement or social media post that was trying to influence your belief in some way (or, if you're feeling creative...make up your own advertisement or social media post to influence others). Identify at least two of the cognitive biases that might influence your (or others’) beliefs about this post. Make sure you describe how that bias is relevant to the image. (e.g., "in this advertisement, our professor who has authority over our grades is telling us to DRINK TAP WATER.")

3.  **Write about reading.** What is the experience of reading like for you(as a kid, in school, outside of school, etc.)? What do you like to read (for fun or school)? Have you ever read an academic article for psychology? Where / why? What was that experience like? What is something you learned, or a question you had, about academic journals or the peer-review process?

4.  **ON VISION BOARD :** Look over the [Dig Deeper description and rubric](/rm/notes/digdeeper.html). The TLDR is that you are going to compare and contrast some "Pop Psych" finding (as reported in the news media, TikTok, textbook) to the actual scientific article that was the basis for this article. **For this first step :** Find a specific psychological “finding” or “result” as reported in a pop psychology source. Psychology findings are commonly written about in major news outlets like the [StudyFinds.org](http://studyfinds.org/), [New York Times](https://www.nytimes.com/topic/subject/psychology-and-psychologists?mcubz=0), [Vox Media](https://www.vox.com/psychology), [Time Magazine](http://time.com/tag/psychology/), [Vice](https://www.vice.com/en_us/topic/psychology), [Buzzfeed](https://www.buzzfeed.com/search?q=psychology), or podcasts. You could also find a claim as reported in TikTok, Instagram post, or whatever other social media source you are finding. The more specific the better; something like "A recent study from the School of Life found that taking classes at DVC leads to higher psychological well-being" would be more specific than "research over thirty decades says childhood trauma is related to adult well-being." [***You do not need to find the original research article yet!***]{.underline}

**REPLY TO ANOTHER STUDENT'S POST :** Choose one! Reply on Canvas.

-   Add some variables to the student's linear model that might be related to the DV.

-   Add some other cognitive biases that are relevant to the shared advertisement, or think about how the advertisement could add other cognitive biases (e.g., the advertisement of the FRESH TAP WATER could sparkle more to be more alluring / memorable and increase AVAILABILITY BIAS.)
