---
title: ""
format: html
editor: visual
navbar: false
---

## Week 9 - Wednesday, April 1st

### Class Goals

1.  Review Dig Deeper results.
2.  Define, Critique, and Create an Experiment.
3.  Students all learning; Professor not rushing; we all enriched and nourished by knowledge of research methods.

:::::: {.callout-note collapse="true"}
### Announcements and Agenda

::::: columns
::: {.column width="50%"}
-   **No Class Next Week.** Bonus Spring Break. No foolin.
-   **Dig Deeper Assignment.** How y'all wanna do this???
:::

::: {.column width="50%"}
-   **11:10 - 11:50.** Check-In and Dig Deeper Review.
-   **11:50 - 12:35.** Experimental Methods.
:::
:::::
::::::

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/9_causation.html" width="100%" height="500px" title="" border="5px"></iframe>
```

### Useful Links

-   [**CHECK-IN : tinyurl.com/twitterpattern**](https://docs.google.com/forms/d/e/1FAIpQLSf8Fo8cJBEUGCYlMg75pnYjFKqriEGVFRYYQOIsSPvEAcIszg/viewform)
-   [Dig Deeper Assignment](/rm/notes/digdeeper.qmd)
-   [Vision Board](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)

## Before Next Class

### Readings for Class Week (and our Quiz)

1.  [**Sampling Error**](https://youtu.be/fp1xsBMSBg0)**.** Professor recorded a video on sampling error and sampling bias, and a stats review of null hypothesis significance testing. We will review next class....come with questions?
2.  [**Critical Questions to Evaluate Sampling Bias**](https://youtu.be/-KE3pTzYljs)**.** Professor narrates a video to help evaluate whether a sample is biased or not, and how this bias might influence the results.
3.  [**“A WEIRD View of Human Nature”**](https://www.dropbox.com/s/p9rszc3afaiwmcs/2010_WEIRDinScience.pdf?dl=0)**.** A short article that describes how most psychologists get samples for their studies. Focus on : the definition of WEIRD, how frequently psychologists conduct cross-cultural research, how different types of results in psychology differ depending on culture.
4.  [**Chapter 7, Section 36**](https://kpu.pressbooks.pub/psychmethods4e/chapter/conducting-surveys/)**.** From your textbook, on samples and populations, and different forms of sampling biases.

### Week 9 Discussion Questions.

**Last one of the semester. Post in the VISION BOARD and only the VISION BOARD.**

1.  Focus on the article you are using for the DIG DEEPER project. Write out the main idea from the article as a linear model.

2.  Who is the population for this research question, and why are they the population?

3.  Include a screenshot (or copy or paste the text) with information about the sample described in the research article. (If there was more than one study, choose one that you are most interested in.)

4.  Does this sample seem representative of the population? Why / why not?

5.  FINALLY : include any questions you have about sampling error. I know y'all have questions...this stuff is confusing so put SOMETHING here it takes a village to learn so asking questions is part of the village I guess this metaphor is going nowhere...

6.  REPLY TO ANOTHER STUDENT : look over their response...explain how a different sample of people (or animals) studied might influence the results.
