---
title: ""
format: html
editor: visual
navbar: false
---

## Week 14 - Wednesday, May 20th

### Class Objectives

1.  20 MIN : Evaluating Posters
2.  30 MIN : Working on Your Posters
3.  25 MIN : Research Methods is Over. Long Live Research Methods.

### Class Slides

```{=html}
<iframe data-external="1" class="slide-deck" src="/rm/slides/14_TheEnd.html" width=100% height="400px"></iframe>
```

### Useful Links

-   **ANONYMOUS CHECK-IN : [tinyurl.com/byebyeRM](https://docs.google.com/forms/d/e/1FAIpQLSfKQ3ZKHjlkjnyKtOcoTRUP_H1prXmRTfyGkwlSB_z_lsKwhg/viewform?usp=sf_link)**
-   [**Final Project Description & Rubric**](https://docs.google.com/document/d/1QJKm9s8WUXAoYACf_pC9QIWdYyfEOHQNMnP4unkXGYI/edit?usp=sharing)
    -   [**Poster Examples**](https://www.dropbox.com/scl/fi/3ieqzi1qc3xmu719jmehu/Poster_Examples_RF.pdf?rlkey=1hh1qzarepidni0affnst6ps5&dl=0) A collection of all the posters that I passed around. DO NOT READ ALL OF THESE. Useful just to get a sense of the genre.

    -   [**FINAL PROJECT POSTER TEMPLATE**](https://docs.google.com/presentation/d/12vZTjpoXdL0tRVkxrvv1aVmKC657HUuzKng0mg9COPI/edit?usp=sharing)**.** Keepin' it Simple.

    -   [**Vision Board**](https://docs.google.com/spreadsheets/d/14u3w5edvo6KSFRw2U9t1knDANFSGBWOvDjS7-ZGujos/edit?usp=sharing)

:::{.callout-tip collapse = "true"}

### Would You Like To Learn More (About Research?)

-   Talk to folks doing the work YOU want to be doing.

-   Get Experience When You Transfer.

    -   Look for an “RA” (Research Assistant) Position

    -   Look for a faculty who seems like they do cool research → email one of their grad students (or them! Be bold!)

        -   Hi, my name is blah blah. SOMETHING COOL / INTERESTING ABOUT YOU GOES HERE! I’m super interested in PROFESSOR / GRAD STUDENT RESERACH TOPIC GOES HERE and looking to gain more research experience. My goal is (YOUR RESEARCH-RELATED GOAL GOES HERE). Do you have any open RA positions, or know of any other research opportunities? Next semester, I’ll be available to commit to X hours a week.

    -   Focus on SEEKING EXPERIENCES you can write about (and show off) : discussing research articles, working with participants, analyzing and presenting data, doing your own independent research, making connections w/ other researchers (at transfer school; at conferences).

:::

## The End!
