---
title: "Lab2"
format: html
---

[Link to this page as a .qmd file.]

### Problem 1. Self-Esteem Problems

[Link to Dataset and Codebook (also on bCourses under "Datasets" folder)](https://www.dropbox.com/scl/fo/g3gd5cxo5hkkb7bs82yf7/AKYclfdqjPaAQ-P34YZcA9o?rlkey=afi2203cqei3ecu0mlfph59vw&dl=0)

Psychologists often want to combine information from multiple questions (that measure the same construct) into one variable. For example, the Rosenberg (1965) self-esteem scale has 10 questions all related to self-esteem; rather than work with 10 different variables, it might be nice to just average these 10 and report one average number.

**Use the self-esteem dataset (from the class datasets folder). You should find a codebook that describes these data in the same folder.**

1. Check to make sure the data loaded correctly. Report the sample size of the dataset.

2.  Create a self-esteem scale from the 10-items. Make sure to reverse-score the negatively-keyed items so that for every question, higher numbers measure higher self-esteem. Graph this variable as a histogram, and make the graph look nice (ready for publication).

3.  Report the alpha reliability, mean, and standard deviation of this variable. Below your graph, describe what these statistics tell you about the self-esteem of the participants. What other questions do you have about this variable, or the output?


### Problem 2 - Practicing Linear Models Increases Self-Esteem

Using the self-esteem variable you created, determine whether there is a relationship between self-esteem and age. Include a graph of your linear model, and report the intercept, slope, and $R^2$ from the model. Below these statistics, explain what they tell you about the relationship between these two variables, and how you can see them on the graph.


### Problem 3. My Own Measure

In the Week 2 Vision Board, write some items (positive and negatively keyed) that would measure a variable you are interested in studying. I've pasted the variables from Week 1, but feel free to change as your interests update :). I've posted an example to help get y'all started. You can also see if there's an "official" or previously published scale to use or draw on - if so, just link to that source, and paste a few example positive and negatively keyed items.
