---
title: "Lab3"
format: html
---

### [Link to Dataset, Codebook (also on bCourses under "Datasets" folder)](https://www.dropbox.com/scl/fo/kqksf8pyykxihfcueq0am/AFAcAshtuveahjw2jlo5Ew8?rlkey=0j0rzco09duz2azun03op96cp&dl=0)

These data come from a study on measuring people's attitudes about conspiracy beliefs (included in the folder, alongside the dataset and codebook). Questions 1-15 in the dataset focus on the conspiracy beliefs scale (see the codebook for full details.)

*NOTE : the value 0 in the dataset was used to indicate that data were missing. You will need to convert 0s in the entire dataset to NA values.*

### **Prepare a short (1-2 page!) report in Quarto that answers the following questions:** 

1.  **How do people differ in terms of their general beliefs about conspiracy theories?** Create a likert scale for the 15 conspiracy belief items, and report descriptive statistics for this variable.
2.  **Are men different from women in their conspiracy beliefs?** Define a linear model to predict your conspiracy beliefs scale from the variable gender. Note that gender was measured as a categorical variable, so will need to be converted from numeric.
3.  **Estimate the probability that the pattern you observed above is due to chance**. Use NHST methods to answer this question, but also try to use bootstrapping. Okay if you get stuck! We will continue to practice - just try and explain why / how you got stuck.
4.  **Were all the assumptions of linear regression met for this linear model?** Evaluate this model in terms of the assumptions of linear regression (which you can read about in our weekly notes.)
5.  **Repeat the steps above to predict the conspiracy beliefs scale from another independent variable from the dataset.** Make sure to a) do any data cleaning necessary to define this other independent variable, b) describe the relationship between this new predictor and conspiracy beliefs, c) determine whether the relationship is statistically significant or not, and d) evaluate the assumptions of the model.
6.  **Conclude :** which model do you think is a better predictor of conspiracy beliefs? Why?
