---
title: "COMPSS 212 - Applied Statistics I"
format: html
editor: visual
---

**Lecture (3 Units) \|** Mondays, 10:00 AM - 12:00 PM, in the MaCSS Classroom (2121 Allston Way).

**Prof. \|** Arman Catterson, PhD \[he / his / او \] 🐱([catterson\@berkeley.edu](mailto:catterson@berkeley.edu)). Office hours are Mondays, 12:00 - 1:00 PM in the MaCSS Classroom. If this time doesn’t work, e-mail or talk to me after class to find a time that does!

**GSI \|** Yi-Ke Peng \[\]. Office hours are TBD.

**Textbooks \|** We’ll be drawing from two open-sourced textbooks. [Regression and Other Stories (ROS; note there is a free PDF of the textbook on the website)](https://avehtari.github.io/ROS-Examples/index.html) will go deeper into the statistics material, whereas The Handbook of Social Psychology (HSP) will go deeper into research-methods content required for this course. [Why Statistics (WS)](https://docs.google.com/document/d/1dpODY7iojvMeQMS9xiAo9cThAL7Zz1iLFMXimb-0gbk/edit?usp=sharing) and [Learning Statistics With R (LSR)](https://learningstatisticswithr.com/book/) will serve as an optional review of statistical content in R that students may need for this course depending on their past experience. 

**Prerequisites \|** Students are expected to have working knowledge of both R and statistics basics (e.g., descriptive statistics, linear models). Review material will be provided for students who need additional support.

**Course Descriptions \|** The goal of this course is to teach students the statistics and research methods required to analyze diverse datasets to answer (and generate new) questions, help design and critique methods of measurement and research, and create clear and reproducible reports to share their knowledge and insights.

## Course Outline

*NOTE : Schedule subject to change; professor will make announcements and updates on bCourses.*

+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
|          |                                                                       |                                                                                                                                                                                                                              |                                                       |
+==========+=======================================================================+==============================================================================================================================================================================================================================+=======================================================+
| **Date** | **Class Topic**                                                       | **Support Readings**                                                                                                                                                                                                         | **Lab Assignment**                                    |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 8/31     | **Objective Science :** Quarto, Reliability & Validity                | WS 2-7; LSR 15.1 - 15.2; [HSP : The Who of Psychology](https://openpublishing.princeton.edu/read/the-who-of-social-psychology-the-challenges-of-humans-studying-human-behavior/section/032b1ec1-3e25-48bb-b35c-3c5ecf1de1af) | Lab 1 : BMI and Steps (Health Data)                   |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 9/7      | **No Class :** Labor Day                                              | ROS 2; WS 5                                                                                                                                                                                                                  | Lab 2 : Likert Scales (MC Quiz)                       |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 9/14     | **Constructing Reality :** Operationalization and Likert Scales       | [HSP : Measuring Constructs](https://openpublishing.princeton.edu/read/measuring-constructs/section/ac12c4e3-9b41-4dab-a61d-0c6615869b75)                                                                                    | Lab 3 : Love in R (Survey Data)                       |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 9/21     | **Faking Data is Good, Actually :** Simulating Data; Bootstrapping    | ROS 5; WS 8; LSR 9-10                                                                                                                                                                                                        | Lab 4 : More Doors, More Problems (Simulated Data)    |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 9/28     | **Lines Can Have Errors :** Linear Model Review and Assumptions       | ROS 7 & 11                                                                                                                                                                                                                   | Lab 5 : Objective Lines (Author Data)                 |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 10/5     | **Experiments for Fun (and Profit) :** Treatment Effects              | ROS 18; [HSP : Art of Experimentation](https://openpublishing.princeton.edu/read/the-art-of-experimentation-in-the-laboratory-and-online/section/095ef473-ba57-4b6a-ad21-77c6882ee48c)                                       | Lab 6 : Replicating Experiments (Dehumanization Data) |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 10/12    | **We Could Always Be Wrong :** Power and P-Hacking                    | [HSP : Changing Practices](https://openpublishing.princeton.edu/read/changing-practices-and-priorities-in-social-psychological-research-methods-and-reporting/section/cacd7484-717d-4bfa-9d30-45ed53db53d0)                  | Lab 7 : More Power, More Practice                     |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 10/19    | **Life is Complex :** Multiple Regression (Still a Line)              | ROS 10.1-10.2; WS 10; [HSP : Field Research](https://openpublishing.princeton.edu/read/field-research-five-approaches-to-theoretical-development-in-the-field/section/3ec25c7a-19b2-4a0b-8176-813d5091d66d)                  | Lab 8 : Nudging R (Field Data)                        |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 10/26    | **Life Depends :** Interaction Effects (Also Lines)                   | ROS 10.3; WS 11                                                                                                                                                                                                              | Lab 9 : Feels Good to Be Here (Self-Esteem Data)      |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 11/2     | **Review and Catch-Up :** How are we doing at this point in time?     |                                                                                                                                                                                                                              | Lab 10 : Practice Exam                                |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 11/9     | **BRAIN EXAM + R EXAM**                                               |                                                                                                                                                                                                                              |                                                       |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 11/16    | **Never Tell Me The Odds :** Generalized Linear Models (Bendy Lines)  | ROS 15; WS 12                                                                                                                                                                                                                | Lab 11 : Project Milestone 1                          |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 11/23    | **Multilevel Models.** Random Slopes, Random Intercepts, Still Lines. | ROS 22.5                                                                                                                                                                                                                     | Lab 12 : It Depends (Football Data)                   |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 11/30    | **Multilevel Models, Part 2 :** Time-Series Data.                     | ROS B                                                                                                                                                                                                                        | Lab 13 : Project Milestone 2                          |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+
| 12/7     | **Presentations.** We learn from each other.                          |                                                                                                                                                                                                                              |                                                       |
+----------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+

## **Grade Details**

Your grade in the class will be based on the following components.

+-------------------+---------------------+--------------------+------------------+
|                   |                     |                    |                  |
+===================+=====================+====================+==================+
| 30% Participation | 30% Lab Assignments | 20% Brain & R Exam | 20% Presentation |
+-------------------+---------------------+--------------------+------------------+

**Letter grades will be based on the following cutoffs :**

+---------------+---------------+----------------+--------------------------+
|               |               |                |                          |
+:=============:+:=============:+:==============:+:========================:+
| A+ is \> 96.5 | B+ is \> 86.5 | C + is \> 76.5 | D is \> 59.5             |
|               |               |                |                          |
| A is \> 92.5  | B is \> 82.5  | C is \> 72.5   | F is \< 59.5             |
|               |               |                |                          |
| A- is \> 89.5 | B- is \> 79.5 | C- is \> 69.5  | note : an 89.499 is a B+ |
+---------------+---------------+----------------+--------------------------+

## About This Class

Read the tabs below for more information about our class. Let me know if you have any questions or spot errors.

::: panel-tabset
#### Course Components.

**Participation (Lecture and Discussion Section Attendance, Vision Board & Check-In Completion):** Because we all learn from each other; in-person attendance is required. You may miss up to two lectures and discussion sections with no penalty. Lectures will be recorded for students who want to review the material they missed (however watching the recording does not count toward your attendance.) Lectures will be recorded for those who need to miss, and students have 1-week after the lecture to complete the check-Ins and vision board assignment (with no penalty).

**Lab Assignments :** Each week, you will work through a “lab” assignment that is designed to help practice the skills we review in lecture and readings. You can expect to work on these in lecture, in discussion sections, and at home as needed. Each lab document will have a set of questions to answer - you should submit answers to these questions as a separate document to bCourses. Lab assignments are due the week after they are assigned. You can drop your lowest submitted lab assignment.

**Final Project (Research Presentation) :** You’ll apply the skills you have learned in the class to prepare a report and / or presentation that includes both survey and experimental methods that addresses a research question relevant to your interests. See the Final Project Description & Rubric for more information.

**Brain & R Exams :** During the exam week, you will take an in-class, paper based exam that assesses your ability to interpret statistical results. You will then be assigned an open-note and take-home exam that asks you to answer a series of research questions based on the data. Accommodations can be made for students who need extra time or translation services.

**Extra Credit :** There will be no extra credit offered in this course, even for students who ask kindly.

#### Course Policies.

**Late Work Policy.** Labs assignments are due before lecture, the week after they are assigned. Late assignments will be penalized 25% for any reason (even if they are 1-minute late), and 50% if turned in more than a week late (after the key has been posted). Students with extra time DSP accommodations should work out a plan to submit work within a week of the original deadline. Students may drop their lowest submitted lab assignments. Note : in the past, I’ve tried a variety of more lenient late-work policies, and found that these policies often disincentivized students turning in work on time to their overall detriment in the class; so let’s try this and see how it goes.

**Computer Access.** Access to a personal computer is required We will spend time each lecture working in R - a free and powerful statistics program that works with all operating systems and computers. Laptops are available for rent from the library (see [Berkeley’s Technology Loan Program](https://studenttech.berkeley.edu/devicelending)), or you can purchase one that will work for this class for as little as \$150 (less than the price of most textbooks, which is not required for this class). Talk to me or a GSI if access to a laptop or computer is interfering with your ability to do well in the course.

**Regrades.** Students may ask for a re-grade on exams and papers if they believe they lost points for something they should have earned. To request a regrade, talk to your GSI in office hours or set up a meeting. In the case that you and your GSI cannot resolve the regrade issue, the professor will step in and regrade the exam. For final project regrades, just e-mail the professor. When requesting a regrade, you consent to have your score increased or decreased if we find that you earned points you should not have earned.

**Student Contact.** It is your responsibility to regularly check e-mail for announcements. Please post questions about the class or R to our class discord page, so other students can see the question (and answer) and benefit from your question! If you have specific questions to e-mail me, please make sure to (a) search the syllabus and / or Google for the answer to your question and (b) contact your GSI about your question. I am always happy to answer any questions in office hours (either during the scheduled time or online by appointment), or before, during, or after lecture. I should respond to e-mail within 24 hours on weekdays (I do not check e-mail on weekends); please send a gentle reminder if I do not respond in this timeframe. Thanks!

**Incomplete Policy.** I will only grant an incomplete to students who (1) have a significant life event that prevents them from completing the final project at the end of the semester and (2) are passing the class at the point they request the incomplete.

**Academic Integrity**. Do NOT cheat. Do NOT plagiarize. To copy text or ideas from another source (including your own submitted coursework) without appropriate reference is plagiarism. You may work on lab assignments with other students, but should be able to understand what you are doing. You may not work with other students on the R exam. Anyone caught cheating or plagiarizing will receive a zero on the assignment or test, and **will** be reported to the Office of Student Conduct. It is your responsibility to read the official Student Conduct Policy for more information about campus standards and policies regarding Academic Integrity.

**AI Policy.** Generative AI tools should be used to support - not replace - your learning. All students must disclose how they used generative-AI software for each assignment (writing, coding, troubleshooting, etc.). If you used AI tools in any way (e.g., idea generation, writing, editing, troubleshooting or generating R code, etc.) you must include an appendix at the end of the assignment where you include screenshots of your specific queries and answers. Failure to be transparent about the use of AI tools - or feeding an assignment into an AI tool and using the output to completely replace your own work - will result in a zero of the assignment and a scheduled meeting in office hours. Multiple violations of this policy will result in the professor submitting a report to the Academic Integrity office and an F in the class. This is a new technology that we are all figuring out, so ask me if you have questions about this policy, or want to chat more about ways to use (or not use) AI in this class. I ultimately want to see that you are learning the material, and that any AI tools that you use are helping YOU learn, and not replacing the learning process. Whew!!

**Respect for Others.** We **all** belong in our classroom, and I hope that everyone feels free and supported to express our identities when relevant. To achieve this goal, make sure that you are treating others with respect in this course. This means considering others’ opinions and perspectives, making sure not to generalize to groups (or ask students to be representatives of their group), and being mindful of the words that you use. (Also remember that nothing is ever really deleted from the internet, so please be extra mindful of the words you use.) While I will be monitoring class posts and communication, feel free to reach out to me if you see another student engaging in disrespectful or threatening behavior. Of course, this extends to me as well - if you feel like there are parts of the course instruction, subject matter, or class environment that create barriers to your success or inclusion, please contact me via e-mail and trust that your voice will be heard and I will not punish you for offering constructive criticisms of my teaching. I’m very open to learning how to be a better teacher, and always learn a lot from my students. 

**Sensitive Subjects.** Our class will touch on important and potentially sensitive topics that are related to social science and data, such as racism, depression, sex, and poverty. These topics can generate strong emotional responses in students for a variety of reasons - such as their own past histories with these topics or their reactions to the ways the information is presented or described. I will try to make sure to give you a heads up when we start to discuss these topics so you can be mindful of your reactions.

**Strategies for success**. Do your readings, complete assignments on time, understand how the topics and information relate to what you’ve learned (and are learning), and if you don’t understand something, please ask the question!

**Most important.** Please let me know as soon as there is anything going on in your life that you think may affect your ability to do as well as you would like in this class (e.g. sickness, work, small children at home, threats to immigration status, etc.), and I will do my best to work with you on a plan to succeed in the class. If you're not comfortable talking to me directly, you can talk to your TA who can talk to me about your issue.

#### Student Support Services.

UC Berkeley offers a variety of services to help support students facing difficulties in these historic times.

**Students with Disabilities :** Students who require support or adaptive equipment because of a specific disability -- or would like to be tested to see if they qualify for a learning, auditory, or visual disability -- can request these services through the Disabled Students Program (DSP) office. Please note that I can only provide accommodations authorized by the DSP office. If you have DSP status, make sure you submit your letter and feel free to talk to me or a GSI about any specific accommodations you need, or other ways we might be able to make the class more accessible. \[260 César E. Chávez Student Center\| 510-642-0518 \| <https://dsp.berkeley.edu/>\]

**Students with Mental Health Issues :** If you feel a mental health issue (e.g., depression, anxiety) is negatively impacting your ability to succeed, I’d highly encourage you to seek out experts who can help. Berkeley has several free, confidential, and science-based programs designed to help students. \[<https://uhs.berkeley.edu/caps> \| Tang Center 3rd Floor \| 510-642-9494 \| After hours support line : 855-817-5667\]

**Undocumented Students :** I believe that all people deserve equal access to education. The UC Berkeley Undocumented Student Program has organized resources to support undocumented students, protect their rights, and offer potential financial aid \| <https://undocu.berkeley.edu/>

**Students from Low-Income Backgrounds :** The Extended Opportunity Program (EOP) provides college support services for low-income students. Services include additional counseling, financial assistance (study-time parent grants, work-study assignments, and book vouchers), child-care opportunities, and assistance transferring to four-year colleges. \[119 César E. Chavez Student Center \| 510-642-7224 \| <https://eop.berkeley.edu/>\]

**Free On-Campus Tutoring :**

- **The[Data Peer Consulting program](http://bit.ly/data-peer-consulting) in the Division of Computing, Data Science, and Society.** This program strives to help make data science accessible across the broader campus community, by aiming to help undergraduate students, graduate students, staff, and faculty with research project infrastructure or other projects and modules that incorporate data. 

- **The UC Berkeley [D-Lab](http://dlab.berkeley.edu/services)**. Drop-in consulting where people may be able to help you with R specific problems.

- [**Librarians are great**](http://www.lib.berkeley.edu/help/research-help). They can help you find research articles for your final project, think about how to organize or structure your literature review, and probably have other powers from a life of being surrounded by books.
:::
