---
title: ""
format: html
editor: visual
---

# Week 4 - Monday, September 28th

::: {.callout-note collapse = "true"}
### Announcements and Agenda

**Announcements**

- **Lab 2 Key Posted.**
- **Some changes to this course (based on your exit survey feedback; thanks!!!)**
  - **no coding for check-ins :** professor code will save in real-time.
  - **readings :** will introduce topics; offer for students wanting to go deeper.
  - **we wanna learn a ton :** review of "basics" –\> new material.
  - **the program is a lot :** we have this 1 year...can continue to voice some of the ideas and comments you have; please continue let me know what feels helpful (or not) in this class.

**Agenda**

- **10:10 - 11:00.** Check-In (no R) & Multivariate Models
- **11:00 - 11:10 :** BREAK TIME
- **11:10 - 12:00 :** Sampling Error with Bootstrapping (Whew)
:::

### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/COMPSS212/slides/4_MRBoot.html" width="100%" height="500px" title=""></iframe>
```

- [**Check-In (no R!) : 2 Models**](https://forms.gle/gaKpikRoyqANKQDr9) **:** Please use the regression output to answer these questions. No R required; just interpretation.
  - [**Dataset of the Week**](https://www.dropbox.com/scl/fi/97h771dt55vum5lhpf9ng/haas_hormone_dataset.csv?rlkey=sc5rvwdmtjn5inuqm1xok5bwd&dl=0) **:** The "Hormone" Dataset
  - [**VISION BOARD**](https://docs.google.com/spreadsheets/d/14y4W9LJk1I9M3HFIOp3_94tdM0qUSYfkGdZnKK6L23c/edit?usp=sharing).
- [**Professor Notes**](https://www.dropbox.com/scl/fo/7yhs2afoyisskz3eynnh8/ABO5kzYAdp8Y9cDBsqFU_TI?rlkey=hx72km35b6n02ep59vywdy7o4&dl=0). My R scripts and other notes, saved in real-time.

# For Next Week.

### Complete [Lab 4](/COMPSS212/labs/Lab4.html)**.**

### Support Materials

#### More on Multiple Regression

- [***Why Statistics?*** **Chapter 10 - Multiple Regression.**](https://catterson.github.io/ystats/chapters/10R_MultipleRegression.html)A chapter that goes into how to interpret and conduct multiple regression, with some additional examples and videos.

<!-- -->

- **Additional Readings :** For students who want to learn more!
  - [The Difference Between “Significant” and “Not Significant” is not Itself Statistically Significant](https://sites.stat.columbia.edu/gelman/research/published/signif4.pdf)
  - [A conceptual review of mediation, and tour through the 'mediation' package.](https://library.virginia.edu/data/articles/introduction-to-mediation-analysis)
  - Preacher KJ, Hayes AF. Asymptotic and resampling strategies for assessing and comparing indirect effects in multiple mediator models. Behav Res Methods. 2008;40(3):879-891. doi:10.3758/BRM.40.3.879
  - [A nice and recent summary of why caution is needed for mediation analysis.](https://www.the100.ci/2025/03/20/reviewer-notes-thats-a-very-nice-mediation-analysis-you-have-there-it-would-be-a-shame-if-something-happened-to-it/)
