---
title: ""
format: html
editor: visual
---

# Week 5 - Monday, October 4th

::: {.callout-note collapse="true"}
### Announcements and Agenda

**Announcements**

- **Lab 2 Key Posted.**
- **Some changes to this course (based on your exit survey feedback; thanks!!!)**
  - **no coding for check-ins :** professor code will save in real-time.
  - **readings :** will introduce topics; offer for students wanting to go deeper.
  - **we wanna learn a ton :** review of "basics" –\> new material.
  - **the program is a lot :** we have this 1 year...can continue to voice some of the ideas and comments you have; please continue let me know what feels helpful (or not) in this class.

**Agenda**

- **10:10 - 10:50.** Check-In (no R) & Multivariate Models
- **10:50 - 11:00 :** BREAK TIME
- **11:00 - 12:00 :** Interaction Effects
:::

### Class Slides and Materials

```{=html}
<iframe data-external="1" class="slide-deck" src="/COMPSS212/slides/mrexperiment_slides.html" width="100%" height="500px" title=""></iframe>
```

- [**Check-In (no R!) : 3 Models**](https://forms.gle/gBixuzC9jDksnokJ8) **:** Please use the regression output to answer these questions. No R required; just interpretation.
  - **Dataset of the Week:** The "Salaries" Dataset from the car library in R `?car::Salaries`
  - [**VISION BOARD**](https://docs.google.com/spreadsheets/d/14y4W9LJk1I9M3HFIOp3_94tdM0qUSYfkGdZnKK6L23c/edit?usp=sharing).
- [**Professor Notes**](https://www.dropbox.com/scl/fo/7yhs2afoyisskz3eynnh8/ABO5kzYAdp8Y9cDBsqFU_TI?rlkey=hx72km35b6n02ep59vywdy7o4&dl=0). My R scripts and other notes, saved in real-time.

# For Next Week.

### No Lab.

### Support Materials

- [**Meyer et al. (2001) article**](https://www.dropbox.com/s/r0uwvdqezzvlvdb/2001_Meyer_EffectSizes.pdf?dl=0) **on effect sizes.** You do not need to read all of this article, and promised me you would not in class! [**Here’s a video professor recorded**](https://www.loom.com/share/3228d91e431e4be4b3f1c871df7f1db3?sid=0f022c43-6667-447e-b63c-7be544e9643b) in a previous semester walking through how to navigate this article to answer some similar questions I'm asking this semester. (I cut a few steps (and hadn't yet seen the light of the vision board....), but this should give you the general idea.)
